#ifndef _PROCCTRL_TUI_H
#define _PROCCTRL_TUI_H

#define PROCCTRL_DISPLAYMODE_HELP      1
#define PROCCTRL_DISPLAYMODE_CTRL      2
#define PROCCTRL_DISPLAYMODE_RESOURCES 3
#define PROCCTRL_DISPLAYMODE_TRIGGER   4
#define PROCCTRL_DISPLAYMODE_TIMING    5
#define PROCCTRL_DISPLAYMODE_HTOP      6
#define PROCCTRL_DISPLAYMODE_IOTOP     7
#define PROCCTRL_DISPLAYMODE_ATOP      8

#endif
