#!/bin/bash

# Early-exit help flags
case "${1-}" in
    -h1|--help-oneline)
        echo "purge orphan shared memory streams and files"
        exit 0 ;;
    -h2|--help-description)
        echo "Remove orphan shared memory image" \
             "streams and associated files. An" \
             "optional filter string can be" \
             "specified to match stream names."
        exit 0 ;;
    -hm|--help-mono|-h|--help) ;; # fall through
esac

# number of arguments to script
NBARGS=0

# ======================= PROCESS NAME =================================
pname=`echo "$0" | sed "s/\.\///g"`
echo "pname = $pname"

function printHELP {
    echo "------------------------------------------------------------------------"
    echo "$(tput bold) $pname : purge orphan streams $(tput sgr0)"
    echo "------------------------------------------------------------------------"
    echo "  Remove orphan shared memory image (stream) and associated files"
    echo "  Optional filter string to be matched can be specified"
    echo "   "
    echo " $(tput bold)USAGE:$(tput sgr0)"
    echo "     $0 [-hf:]"
    echo ""
    echo " $(tput bold)OPTIONS:$(tput sgr0)"
    echo "     $(tput bold)-h$(tput sgr0)          (h)elp"
    echo "     $(tput bold)-f$(tput sgr0)          only purge streams matching (f)ilter"
    echo ""
    echo " $(tput bold)SEE ALSO:$(tput sgr0)"
    echo "     milk-rmshmim       remove shared memory stream"
    echo "     milk-shmim-rm      remove stream and files"
    echo "------------------------------------------------------------------------"
}

printHELP1 ()
{
    printf "%20s       Purge orphan streams\n" "$0"
}

# Transform long options to short ones
singlelinehelp=0
for arg in "$@"; do
    shift
    case "$arg" in
        "--help") set -- "$@" "-h" ;;
        "--help1")
            set -- "$@" "-h"
            singlelinehelp=1;
            ;;
        *)        set -- "$@" "$arg"
    esac
done

FILTERSTRING=""

while getopts :hf: FLAG; do
    case $FLAG in
        h)  #show help
            if [ "$singlelinehelp" -eq "0" ]; then
                printHELP
            else
                printHELP1
            fi
            exit
            ;;
        f)
            FILTERSTRING="${OPTARG}"
            echo "using filter ${FILTERSTRING}"
            ;;
        \?)
            echo -e "\n\033[1;31mERROR\033[0m Option -${OPTARG} not allowed."
            printHELP
            exit 1
            ;;
    esac
done

shift $((OPTIND-1))

### End getopts code ###

if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
    if [ "$#" -ne $NBARGS ]; then
        echo -e "\n\033[1;31mERROR\033[0m Illegal number of parameters ($NBARGS params required, $# entered)"
    fi
    printHELP
    exit 1
fi

milk -n ${pname} << EOF
shmimpurge "${FILTERSTRING}"
exitCLI
EOF
