#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# Test semaphore latency
# Sets up two streams, imA and imB
#

# script 1-line description
MSdescr="measure semaphore latency"

# Extended description
MSextdescr="creates 2 streams and 2 processes
process AB waits on imA, pokes imB
process BA waits on imB, pokes imA
"

# standard configuration
#
source milk-script-std-config

# prerequisites
#
RequiredCommands=( milk tmux )
RequiredFiles=()
RequiredDirs=()

# SCRIPT ARGUMENTS (mandatory)
# syntax: "name:type(s)/test(s):description"

MSarg+=( "nbloop:int:number of loop interations" )

# SCRIPT OPTIONS
# syntax: "short:long:functioncall:args[types]:description"

# parse arguments
source milk-argparse

NBLOOP="${inputMSargARRAY[0]}"

SEMTRIG="3"

milk-cli << EOF
mem.mk2Dim "s>imA" 100 100
mem.mk2Dim "s>imB" 100 100
mem.imsetsempost imA -1
mem.imsetsempost imB -1
exitCLI
EOF

set +e
tmux new-session -d -s loopAB
#tmux new-session -d -s loopBA

tmux send-keys -t loopAB "milk-cli" C-M
tmux send-keys -t loopAB "mem.readshmim imA" C-M
tmux send-keys -t loopAB "mem.readshmim imB" C-M
tmux send-keys -t loopAB "mem.shmimpoke ..procinfo 1" C-M

# set trigger mode to semaphore
tmux send-keys -t loopAB "mem.shmimpoke ..triggermode 3" C-M

# set trigger semaphore name
tmux send-keys -t loopAB "mem.shmimpoke ..triggersname imA" C-M

# number of loops
tmux send-keys -t loopAB "mem.shmimpoke ..loopcntMax ${NBLOOP}" C-M

tmux send-keys -t loopAB "mem.shmimpoke imB" C-M
tmux send-keys -t loopAB "exitCLI" C-M

milk-cli << EOF
mem.readshmim imA
mem.readshmim imB
mem.shmimpoke ..procinfo 1
mem.shmimpoke ..triggermode 3
mem.shmimpoke ..triggersname imB
mem.shmimpoke ..loopcntMax ${NBLOOP}
mem.shmimpoke imA
mem.imseminfo imA
exitCLI
EOF

# cleanup

tmux kill-session -t loopAB
milk-shmim-rm imA
milk-shmim-rm imB
