#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions


# script 1-line description
MSdescr="poke existing stream from stream trigger"

# Extended description
MSdescr="poke existing stream from stream trigger
streamOUT is poked when streamTRIG is posted
"

# standard configuration
#
source milk-script-std-config

# prerequisites
#
RequiredCommands=( milk )
RequiredFiles=()
RequiredDirs=()



# SCRIPT ARGUMENTS (mandatory)
# syntax: "name:type(s)/test(s):description"

MSarg+=( "streamnameOUT:string:stream to be poked" )
MSarg+=( "streamnameTRIG:string:trigger stream" )

# SCRIPT OPTIONS
# syntax: "short:long:functioncall:args[types]:description"

NBpoke="0"
MSopt+=( "n:nbpoke:set_NBpoke:nbpoke[long]:loopcntmax (0 = single poke) [${NBpoke}]" )
function set_NBpoke() {
	NBpoke="$1"
}



# parse arguments
source milk-argparse
streamnameOUT="${inputMSargARRAY[0]}"
streamnameTRIG="${inputMSargARRAY[1]}"


echo ${streamnameOUT}

MILK_QUIET=1 milk << EOF

readshmim ${streamnameOUT}
readshmim ${streamnameTRIG}

# Activate processinfo
shmimpoke ..procinfo 1

# Run computation N times
shmimpoke ..loopcntMax ${NBpoke}

# Change triggermode to 3 : semaphore
shmimpoke ..triggermode 3

# set delay
shmimpoke ..triggersname ${streamnameTRIG}

shmimpoke ${streamnameOUT}
listim
exitCLI
EOF
