#!/usr/bin/env bash

if [ -z ${FPSLISTADDSCRIPT+x} ]; then
	echo "crop and mask image"
	echo "Not a standalone script, must be run within cacao-fpslistadd script"
	echo "To activate, add in cacaovars:"
	echo "export CACAO_FPSPROC_WFSCROPMASK=\"ON\""
else




if [ "${CACAO_FPSPROC_WFSCROPMASK}" = "ON" ]; then

    echolog "ON  CACAO_FPSPROC_CROPMASK"
    # ==============================================================================
    # ==========  streamdelay for simulation mode ==================================
    # ==============================================================================

    # FPS name
    fpsname="wfscropmask"
    fpsarg0="${CACAO_LOOPNUMBER}"

    # FPS full name
    fpsfname="${fpsname}-${fpsarg0}"


    if grep -q "${fpsname}" fpslist.txt
    then
        echolog "Process ${fpsname} already registered - skipping"
    else
        echolog "Adding process ${fpsname}"
        echo "${fpsname}    cropmask         ${fpsarg0}"  >> fpslist.txt

        addfpscmdheader

    fi


fi # end of if [ "${CACAO_FPSPROC_WFSCROPMASK}" = "ON" ]

fi # end of if [ -z ${FPSLISTADDSCRIPT+x} ]
