#!/usr/bin/env bash

if [ -z ${FPSLISTADDSCRIPT+x} ]; then
	printf "\e[1;34m[sourced by cacao-fpslistadd]\e[0m FPS add: WFS stream crop"
else

	if [ ! -z "${CACAO_FPSPROC_WFSCROPMASK+x}" ]; then
		echo "CACAO_FPSPROC_WFSCROPMASK set to ${CACAO_FPSPROC_WFSCROPMASK}"


		if [ "${CACAO_FPSPROC_WFSCROPMASK}" = "ON" ]; then

			echolog "ON  CACAO_FPSPROC_WFSCROPMASK"

			# FPS name
			fpsname="wfscropmask"
			fpsarg0="${CACAO_LOOPNUMBER}"

			# FPS full name
			fpsfname="${fpsname}-${fpsarg0}"


			if grep -q "${fpsname}" fpslist.txt
			then
				echolog "Process ${fpsname} already registered - skipping"
			else
				echolog "Adding process ${fpsname}"
				echo "${fpsname}    cropmask         ${fpsarg0}"  >> fpslist.txt

				addfpscmdheader

				addfpscmd "setval ${fpsfname}.insname ${CACAO_WFSSTREAM}"
				addfpscmd "setval ${fpsfname}.procinfo.loopcntMax -1"
				addfpscmd "setval ${fpsfname}.procinfo.triggermode 3"
				addfpscmd "setval ${fpsfname}.procinfo.triggersname ${CACAO_WFSSTREAM}"
				addfpscmd "setval ${fpsfname}.outsname aol${CACAO_LOOPNUMBER}_wfsim"
			fi


		fi # end of if [ "${CACAO_FPSPROC_WFSCROPMASK}" = "ON" ]

	else
		echo "CACAO_FPSPROC_WFSCROPMASK unset"
	fi

fi # end of if [ -z ${FPSLISTADDSCRIPT+x} ]
