# CMake generated Testfile for 
# Source directory: /home/oguyon/src/milk
# Build directory: /home/oguyon/src/milk/build_local
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(standalone-dep-check "/home/oguyon/src/milk/scripts/milk-check-standalone-deps" "/home/oguyon/src/milk/build_local")
set_tests_properties(standalone-dep-check PROPERTIES  _BACKTRACE_TRIPLES "/home/oguyon/src/milk/CMakeLists.txt;696;add_test;/home/oguyon/src/milk/CMakeLists.txt;0;")
subdirs("src/cli/libmilkscript")
subdirs("src/cli/CLIcore")
subdirs("src/engine/ImageStreamIO")
subdirs("src/coremods/COREMOD_arith")
subdirs("src/coremods/COREMOD_memory")
subdirs("src/coremods/COREMOD_tools")
subdirs("src/coremods/COREMOD_iofits")
subdirs("src/sequencer")
subdirs("plugins/OpticsMaterials-src/OpticsMaterials")
subdirs("plugins/coffee-src/OptSystProp")
subdirs("plugins/coffee-src/AOsystSim")
subdirs("plugins/coffee-src/PIAACMCsimul")
subdirs("plugins/coffee-src/coronagraphs")
subdirs("plugins/milk-extra-src/fft")
subdirs("plugins/milk-extra-src/linopt_imtools")
subdirs("plugins/milk-extra-src/linalgebra")
subdirs("plugins/milk-extra-src/image_gen")
subdirs("plugins/milk-extra-src/ZernikePolyn")
subdirs("plugins/milk-extra-src/linARfilterPred")
subdirs("plugins/milk-extra-src/clustering")
subdirs("plugins/milk-extra-src/kdtree")
subdirs("plugins/milk-extra-src/image_basic")
subdirs("plugins/milk-extra-src/info")
subdirs("plugins/milk-extra-src/psf")
subdirs("plugins/milk-extra-src/img_reduce")
subdirs("plugins/milk-extra-src/statistic")
subdirs("plugins/milk-extra-src/image_filter")
subdirs("plugins/milk-extra-src/image_format")
subdirs("plugins/scexao-dataanalysis/vampirespdi")
subdirs("plugins/cacao-src/AOloopControl_perfTest")
subdirs("plugins/cacao-src/AOloopControl_IOtools")
subdirs("plugins/cacao-src/pycacao")
subdirs("plugins/cacao-src/AOloopControl_PredictiveControl")
subdirs("plugins/cacao-src/computeCalib")
subdirs("plugins/cacao-src/AOloopControl_acquireCalib")
subdirs("plugins/cacao-src/AOloopControl_compTools")
subdirs("plugins/cacao-src/AOloopControl")
subdirs("plugins/cacao-src/AOloopControl_DM")
subdirs("plugins/cacao-src/pyramidWFStools")
subdirs("plugins/WFpropagate-src/WFpropagate")
subdirs("src/milk_module_example")
subdirs("src/isio-tools")
subdirs("src/perfbench")
subdirs("src/engine/libmilkcommon")
subdirs("src/engine/libfps")
subdirs("src/engine/libfpsseq")
subdirs("src/engine/libmilkdata")
subdirs("src/engine/libprocessinfo")
