#!/usr/bin/env bash


MSdescr="Simple function test"

scriptname=$(basename $0)

MSextdescr="Simple function test

Computes image total.
Demonstrates use of milk command line interface (CLI) and its interaction
with function parameter structure (FPS) and process information (procinfo)."


source milk-script-std-config

RequiredCommands=( milk tmux nnn )
RequiredFiles=()
RequiredDirs=()

source milk-argparse

SKIP=0

TMUXSESSIONNAME="milkexample"

set +e
echo "list of sessions:"
tmux ls
echo "Ceating session ${TMUXSESSIONNAME}"
tmux new -d -s ${TMUXSESSIONNAME}
echo "list of sessions:"
tmux ls
tmux send-keys -t ${TMUXSESSIONNAME} C-c
tmux send-keys -t ${TMUXSESSIONNAME} "clear" C-m
set -e
echo "Example(s) will run in tmux session ${TMUXSESSIONNAME}"
echo "$(tput bold)Run \"tmux a -t ${TMUXSESSIONNAME}\" to connect$(tput sgr0)"
echo
read -p "Press [ENTER] to clear screen and continue"



function ProbeUserRunExample {
    readarray -t CLIinarray <<<"$CLIinput"
    nbCLIcmd=${#CLIinarray[@]}
    echo "Running example in tmux session \"${TMUXSESSIONNAME}\""
    tmux send-keys -t ${TMUXSESSIONNAME} "clear" C-m
    echo ""
    for (( i=0; i<$nbCLIcmd; i++ )); do
        CLIline=${CLIinarray[$i]}
        if [ -n "$CLIline" ]; then # only process non-empty lines
        if [[ $CLIline == \#* ]]; then
            # this is a comment, just print it in green
            echo "$(tput setaf 2)${CLIline} $(tput sgr0)"
        else
            echo "$(tput bold)$(tput setaf 3)${CLIline} $(tput sgr0)"
            read -p "   Press [ENTER] to run this command in tmux session ${TMUXSESSIONNAME} "
            tmux send-keys -t ${TMUXSESSIONNAME} "${CLIline}" C-m
            echo ""
        fi
        fi
    done
}




ExampleDir="/home/oguyon/src/cream/src/milk_module_example/examples/"

loopOK=1
while [ ${loopOK} = 1 ]; do

#EXAMPLEFILE=$(cd $ExampleDir; nnn -c -o -p '-')
EXAMPLEFILE=$(cd $ExampleDir; nnn -c -o -p '-')

echo "selected : $EXAMPLEFILE in $ExampleDir"
if [ -f "$EXAMPLEFILE" ]; then
    ExampleDir="$(dirname "$EXAMPLEFILE")"
    source $EXAMPLEFILE

    clear
    tput bold; echo "Example ${examplestring}"; tput sgr0
    echo
    echo "$exampleDescription"
    echo
    ProbeUserRunExample
else
    echo "ERROR: File does not exist, could not run test"
fi

echo -n "[ENTER] return to menu or (q)uit ? "
read answer

if [ "$answer" != "${answer#[Qq]}" ]; then
    loopOK=0
else
    loopOK=1
fi


done

# close tmux session
tmux send-keys -t ${TMUXSESSIONNAME} "" C-c
tmux send-keys -t ${TMUXSESSIONNAME} "exit" C-m


echo "End examples"






