#!/usr/bin/env python3
"""
Generates docs/Markdown_Index.md containing links to all markdown files in the repository.
"""

import sys

if len(sys.argv) > 1:
    if sys.argv[1] in ("-h1", "--help-oneline"):
        print("generate markdown documentation index")
        sys.exit(0)
    if sys.argv[1] in ("-h2", "--help-description"):
        print("Scan repo for .md files and generate" " docs/Markdown_Index.md.")
        sys.exit(0)
    if sys.argv[1] in ("-h", "--help", "-hm", "--help-mono"):
        print("Usage: generate_md_index.py")
        print("Generate markdown documentation index.")
        sys.exit(0)

import os
import re
from pathlib import Path


def get_github_repo_info(repo_root):
    """Extract repo_url and edit branch from mkdocs.yml, so the two stay in sync."""
    mkdocs_yml = (repo_root / "mkdocs.yml").read_text(encoding="utf-8")

    repo_url_match = re.search(r"^repo_url:\s*(\S+)", mkdocs_yml, re.MULTILINE)
    edit_uri_match = re.search(r"^edit_uri:\s*edit/([^/]+)/", mkdocs_yml, re.MULTILINE)

    repo_url = repo_url_match.group(1).rstrip("/") if repo_url_match else None
    branch = edit_uri_match.group(1) if edit_uri_match else None
    return repo_url, branch


def get_all_md_files(root_dir):
    md_files = []
    for dirpath, dirnames, filenames in os.walk(root_dir):
        # Exclude common build/git dirs and agent rules
        dirnames[:] = [
            d
            for d in dirnames
            if d
            not in (
                ".git",
                "_build",
                "build",
                ".vscode",
                ".agents",
                ".nox",
                ".pytest_cache",
            )
        ]
        for f in filenames:
            if f.endswith(".md"):
                # Ignore the index itself
                if f == "Markdown_Index.md" and Path(dirpath).name == "docs":
                    continue
                md_files.append(Path(dirpath) / f)
    return md_files


def extract_title(file_path):
    """Attempt to extract the title from the markdown file."""
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            for line in f:
                if line.startswith("# "):
                    return line[2:].strip()
                # If there's front matter, skip it
            return None
    except Exception:
        return None


def main():
    repo_root = Path(__file__).resolve().parent.parent
    index_path = repo_root / "docs" / "Markdown_Index.md"
    github_repo_url, github_branch = get_github_repo_info(repo_root)

    all_md_files = get_all_md_files(repo_root)
    all_md_files.sort()

    # Group by directory relative to root
    groups = {}
    for filepath in all_md_files:
        rel_path = filepath.relative_to(repo_root)
        dirname = str(rel_path.parent)
        if dirname == ".":
            dirname = "Root"
        if dirname not in groups:
            groups[dirname] = []
        groups[dirname].append((rel_path, filepath))

    # Generate markdown content
    content = [
        "# Markdown Documentation Index",
        "",
        "This file is automatically generated by `scripts/generate_md_index.py`.",
        "It provides a complete index of all Markdown documentation available in the repository.",
        "\n"
        "Documentation files will link to this website, other files will link directly to Github.",
        "",
    ]

    for dirname in sorted(groups.keys()):
        content.append(f"## {dirname}")
        content.append("")
        for rel_path, filepath in groups[dirname]:
            title = extract_title(filepath)
            if rel_path.parts[0] == "docs":
                # Part of the mkdocs build: link relative to docs/Markdown_Index.md
                # so mkdocs resolves it within the built site.
                target_from_docs = os.path.relpath(filepath, index_path.parent)
            elif github_repo_url and github_branch:
                # Not part of the mkdocs build: link straight to GitHub, since a
                # relative "../" path would 404 on the published site.
                target_from_docs = (
                    f"{github_repo_url}/blob/{github_branch}/{rel_path.as_posix()}"
                )
            else:
                target_from_docs = os.path.relpath(filepath, index_path.parent)

            if title:
                content.append(f"- [{title}]({target_from_docs}) ({rel_path.name})")
            else:
                content.append(f"- [{rel_path.name}]({target_from_docs})")
        content.append("")

    with open(index_path, "w", encoding="utf-8") as f:
        f.write("\n".join(content))

    print(f"Generated {index_path} with {len(all_md_files)} files indexed.")


if __name__ == "__main__":
    main()
