#!/usr/bin/env python3
"""
Generates docs/Markdown_Index.md containing links to all markdown files in the repository.
"""

import sys

if len(sys.argv) > 1:
    if sys.argv[1] in ("-h1", "--help-oneline"):
        print("generate markdown documentation index")
        sys.exit(0)
    if sys.argv[1] in ("-h2", "--help-description"):
        print("Scan repo for .md files and generate" " docs/Markdown_Index.md.")
        sys.exit(0)
    if sys.argv[1] in ("-h", "--help", "-hm", "--help-mono"):
        print("Usage: generate_md_index.py")
        print("Generate markdown documentation index.")
        sys.exit(0)

import os
import re
from pathlib import Path


def get_all_md_files(root_dir):
    md_files = []
    for dirpath, dirnames, filenames in os.walk(root_dir):
        # Exclude common build/git dirs and agent rules
        dirnames[:] = [
            d
            for d in dirnames
            if d
            not in (
                ".git",
                "_build",
                "build",
                ".vscode",
                ".agents",
                ".nox",
                ".pytest_cache",
            )
        ]
        for f in filenames:
            if f.endswith(".md"):
                # Ignore the index itself
                if f == "Markdown_Index.md" and Path(dirpath).name == "docs":
                    continue
                md_files.append(Path(dirpath) / f)
    return md_files


def extract_title(file_path):
    """Attempt to extract the title from the markdown file."""
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            for line in f:
                if line.startswith("# "):
                    return line[2:].strip()
                # If there's front matter, skip it
            return None
    except Exception:
        return None


def main():
    repo_root = Path(__file__).resolve().parent.parent
    index_path = repo_root / "docs" / "Markdown_Index.md"

    all_md_files = get_all_md_files(repo_root)
    all_md_files.sort()

    # Group by directory relative to root
    groups = {}
    for filepath in all_md_files:
        rel_path = filepath.relative_to(repo_root)
        dirname = str(rel_path.parent)
        if dirname == ".":
            dirname = "Root"
        if dirname not in groups:
            groups[dirname] = []
        groups[dirname].append((rel_path, filepath))

    # Generate markdown content
    content = [
        "# Markdown Documentation Index",
        "",
        "This file is automatically generated by `scripts/generate_md_index.py`.",
        "It provides a complete index of all Markdown documentation available in the repository.",
        "",
    ]

    for dirname in sorted(groups.keys()):
        content.append(f"## {dirname}")
        content.append("")
        for rel_path, filepath in groups[dirname]:
            title = extract_title(filepath)
            # Link generation relative to docs folder
            # Calculate relative path from docs/Markdown_Index.md to the target file
            try:
                # relative_to docs
                target_from_docs = os.path.relpath(filepath, index_path.parent)
            except ValueError:
                target_from_docs = str(rel_path)

            if title:
                content.append(f"- [{title}]({target_from_docs}) ({rel_path.name})")
            else:
                content.append(f"- [{rel_path.name}]({target_from_docs})")
        content.append("")

    with open(index_path, "w", encoding="utf-8") as f:
        f.write("\n".join(content))

    print(f"Generated {index_path} with {len(all_md_files)} files indexed.")


if __name__ == "__main__":
    main()
