#!/bin/bash



# number of arguments to script
NBARGS=1

pname=`basename "$0"`

function printHELP {
    echo "------------------------------------------------------------------------"
    echo "$(tput bold) $pname : CONNECT TO STREAM $(tput sgr0)"
    echo " Full path name : $0"
    echo "------------------------------------------------------------------------"
    echo "  Establishes a stream sym link from TARGET=<sourcestrem> to LINKNAME=<streamname>."
    echo "  Reads conf/streamlink.<streamname>.name.txt to identify source stream."
    echo "  - Create $MILK_SHM_DIR/<streamname>.im.shm that points to $MI_SHM_DIR/<sourcestream>.im.shm"
    echo "  - Runs milk, connects to <streamname> and writes its size to ./conf/streamlink.<streamname>.imsize.txt"
    echo "   "
    echo " $(tput bold)USAGE:$(tput sgr0)"
    echo "     $0 [-h] <streamname>"
    echo ""
    echo " $(tput bold)OPTIONS:$(tput sgr0)"
    echo "     $(tput bold)-h$(tput sgr0)                help"
    echo "     $(tput bold)-p$(tput sgr0) <prefix>       stream prefix"
    echo ""
    echo " $(tput bold)INPUT:$(tput sgr0)"
    echo "     <streamname>           stream name (full name: <prefix><streamname>)"
    echo ""
    echo " $(tput bold)OUTPUT:$(tput sgr0)"
    echo "  ./conf/streamlink.<streamname>.imsize.txt :   stream aimage size"
    echo ""
    echo "------------------------------------------------------------------------"
}


printHELP1 ()
{
    printf "     $(tput bold)%-25s$(tput sgr0)       Connect to shared memory stream\n" "$0"
}





# Transform long options to short ones
singlelinehelp=0
for arg in "$@"; do
    shift
    case "$arg" in
        "--help") set -- "$@" "-h" ;;
        "--help1")
            set -- "$@" "-h"
            singlelinehelp=1;
            ;;
        *)        set -- "$@" "$arg"
    esac
done



SMPREFIX=""
while getopts :hp: FLAG; do
    case $FLAG in
        h)  #show help
            if [ "$singlelinehelp" -eq "0" ]; then
                printHELP
            else
                printHELP1
            fi
            exit
            ;;
        p)
            SMPREFIX="$OPTARG"
            ;;
        \?) #unrecognized option - show help
            echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
            printHELP
            ;;
    esac
done

shift $((OPTIND-1))


fullname="${SMPREFIX}$1"







if [[ -z "${MILK_SHM_DIR}" ]]; then
    echo "ERROR: MILK_SHM_DIR environment variable does not exist: cannot find/access shared memory"
    exit
else
    SHMDIR="${MILK_SHM_DIR}"
fi
echo "SHMDIR = $SHMDIR"






file="./conf/streamlink.$1.name.txt"
if [ -a $file ]; then

    streamname=$( head -1 $file )  # source
    rm $SHMDIR/${fullname}.im.shm  # remove dest
    ln -s $SHMDIR/${streamname}.im.shm $SHMDIR/${fullname}.im.shm  # establish link

echo "Linking ${fullname}"
milk << EOF
readshmim ${fullname}
readshmimsize ${fullname} "./conf/streamlink.$1.imsize.txt"
exitCLI
EOF

fi
