#!/bin/bash

echo ""
echo "milk-cli running in debug mode"
echo "check valgrind output file milk-cli.memcheck.log :"
echo "$ tail -f milk-cli.memcheck.log"
echo ""

cp $(which milk-cli) milkdebugtest
OPTION="--leak-check=full --show-leak-kinds=all"
OPTION="$OPTION --show-reachable=yes"
#OPTION="$OPTION --gen-suppressions=all"
OPTION="$OPTION --log-file=milk-cli.memcheck.log"
OPTION="$OPTION --suppressions=$MILK_ROOT/milk-cli.memcheck.supp"
OPTION="$OPTION --max-stackframe=4442392"

valgrind ${OPTION} ./milkdebugtest
rm ./milkdebugtest
