#!/usr/bin/env bash

MSdescr="milk with all installed modules"


modulelist="milklinalgebra,milkfft,milkimagebasic,milkimagefilter,milkimageformat,milkimagegen,milkimgreduce,milkinfo,milkkdtree,milklinARfilterPred,milklinoptimtools,milkmoduleexample,milkpsf,milkstatistic,milkZernikePolyn"

# Extended description
MSextdescr="Loads modules:
$modulelist
"

source milk-script-std-config



RequiredCommands=( milk )
RequiredFiles=()
RequiredDirs=()

source milk-argparse



MILKCLI_APPNAME="milk-all" MILKCLI_ADD_LIBS="${MILKCLI_ADD_LIBS-};${modulelist}" milk "$@"
