#!/usr/bin/env bash

MSdescr="milk with all installed modules"


modulelist="milklinalgebra,milkfft,milkimagebasic,milkimagefilter,milkimageformat,milkimagegen,milkimgreduce,milkinfo,milkkdtree,milklinARfilterPred,milklinoptimtools,milk_module_example,milkpsf,milkstatistic,milkZernikePolyn"

# Extended description
MSextdescr="Loads modules:
$modulelist
"

source milk-script-std-config



RequiredCommands=( milk )
RequiredFiles=()
RequiredDirs=()

source milk-argparse

# Check if we are running from source directory and MILK_INSTALLDIR is not set
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
ROOT_DIR=$(dirname "$SCRIPT_DIR")
MILK_EXEC="milk"

if [ -d "$ROOT_DIR/_build/lib" ]; then
    echo "Running from source directory, overriding MILK_INSTALLDIR to $ROOT_DIR/_build"
    export MILK_INSTALLDIR="$ROOT_DIR/_build"
    if [ -x "$ROOT_DIR/_build/milk" ]; then
        MILK_EXEC="$ROOT_DIR/_build/milk"
        echo "Using built executable: $MILK_EXEC"
    fi
fi

MILKCLI_APPNAME="milk-all" MILKCLI_ADD_LIBS="${MILKCLI_ADD_LIBS-};${modulelist}" $MILK_EXEC "$@"
