#!/usr/bin/env bash


MSdescr="execute milk command"

MSextdescr="Execute command string within milk command line interface (CLI).
Multiple commands separated by : character"

source milk-script-std-config

RequiredCommands=(milk)
RequiredFiles=()
RequiredDirs=()


MSarg+=( "commandstring:string:command string" )


MSopt+=( "n:name:set_pname:pname[string]:(n)ame process" )
function set_pname() {
    pname="$1"
}

MSopt+=( "T:testmode:set_testmode::(T)est mode" )
function set_testmode() {
    echo "CTEST_FULL_OUTPUT"
}


source milk-argparse





cmdstring="${inputMSargARRAY[0]}"

echo "command string : ${cmdstring}"



IFS=';' read -r -a array <<< "${cmdstring}"

#fifoname="milkCLIfifo.${pname}"
SF="${MILK_SHM_DIR}/milkCLIstartup.${pname}.$$"
echo "" > $SF
for cmdstring in "${array[@]}"
do
    echo "${cmdstring}" >> $SF
done
echo "exitCLI" >> $SF
#cp ${SF} test.txt

milk -n ${pname} -f -s ${SF}

rm ${SF}
