#!/usr/bin/env bash


# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="Establish sym link to stream"


# Extended description
MSextdescr="Establishes a stream sym link from TARGET=<sourcestrem> to LINKNAME=<streamname>
Reads conf/streamlink.<streamname>.name.txt to identify source stream

Reads conf/streamlink.<streamname>.name.txt to identify source stream.
  - Create $MILK_SHM_DIR/<streamname>.im.shm that points to $MI_SHM_DIR/<sourcestream>.im.shm
  - If stream exists, runs milk, connects to <streamname> and writes its size to ./conf/streamlink.<streamname>.imsize.txt
"

# standard configuration
# location ./scripts/
source milk-script-std-config

# prerequisites
#
RequiredCommands=( milk )
RequiredFiles=()
RequiredDirs=()




# SCRIPT MANDATORY ARGUMENTS
# syntax: "name:type(s)/test(s):description"
#
MSarg+=( "streamname:string:link stream name" )



# SCRIPT OPTIONS
# syntax: "short:long:functioncall:args[types]:description"
#
SMPREFIX=""
MSopt+=( "p:prefix:set_SMPREFIX:prefix[string]:stream prefix" )
function set_SMPREFIX() {
	SMPREFIX="$1"
}


# parse arguments
source milk-argparse
linkstreamname="${inputMSargARRAY[0]}"



echo "linking ${linkstreamname}"




if [[ -z "${MILK_SHM_DIR}" ]]; then
    echo "ERROR: MILK_SHM_DIR environment variable does not exist: cannot find/access shared memory"
    exit
else
    SHMDIR="${MILK_SHM_DIR}"
fi
echo "SHMDIR = $SHMDIR"






file="./conf/streamlink.${linkstreamname}.name.txt"
fulllinkname="$SHMDIR/${SMPREFIX}${linkstreamname}.im.shm"
if [ -e $file ]; then

    streamname=$( head -1 $file )  # source

    if [ -e ${fulllinkname}  ]; then
        rm ${fulllinkname}  # remove dest
    fi

    ln -sf $SHMDIR/${streamname}.im.shm ${fulllinkname} # establish link


echo "    Linking ${linkstreamname}: ln -s $SHMDIR/${streamname}.im.shm ${fulllinkname}"



if [ -e $SHMDIR/${streamname}.im.shm ]; then

milk << EOF
readshmim ${streamname}
readshmimsize ${streamname} "./conf/streamlink.${linkstreamname}.imsize.txt"
exitCLI
EOF

fi


else

echo "Cannot find file $file : nothing to do"

fi
