#! /bin/bash

EXPECTED_ARGS=1

if [ $# -ne $EXPECTED_ARGS ]
then
    echo
    echo "-------- STOP LOG SHARED MEMORY DATA STREAM ---------"
    echo " "
    echo "Usage: $0 <data stream name>"
    echo " "
    echo "  INPUT <data stream name>   : shared memory stream name. Actual file is $MILK_SHM_DIR/<stream name>.im.shm"
    echo " "
    echo "EXAMPLE :  $0 ircam2"
    echo " "
    exit
fi

pname="$0-$1"
echo "$pname"



milk-streamFITSlog $1 off

exit

milk -n $pname << EOF
shmimslogonset $1 0
exit
EOF
