#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions


# script 1-line description
MSdescr="milk processinfo control"

scriptname=$(basename $0)




# Extended description
MSextdescr="Monitors and controls milk processes
Connects to $MILK_SHM_DIR/proc.*.shm shared memory structures


"



source milk-script-std-config









# OPTIONS

MSopt+=( "q:q:set_quietmode::(q)uiet mode" )
function set_quietmode () {
	 export MILK_TUIPRINT_NONE=1
}

MSopt+=( "s:s:set_stdiomode::use (s)tdio instead of ncurses" )
function set_stdiomode () {
	 export MILK_TUIPRINT_STDIO=1
}

DEBUG=0
MSopt+=( "d:d:set_debugmode::(d)ebug mode, uses valgrind" )
function set_debugmode () {
	 export DEBUG=1
}


RequiredCommands=( milk )
RequiredFiles=()
RequiredDirs=()


source milk-argparse











ttystring=$( tty | tr -d \/ )
pname="procCTRL"
fifoname="$MILK_SHM_DIR/milkCLIfifo.${pname}.${ttystring}"


SF="$MILK_SHM_DIR/milkCLIstartup.${pname}.${ttystring}"
echo "procCTRL" > $SF
echo "exitCLI" >> $SF

if [ "$DEBUG" = "1" ]; then

    cp $(which milk) milkdebugtest
    OPTION="--leak-check=full --show-leak-kinds=all"
    OPTION="$OPTION --track-origins=yes"
    OPTION="$OPTION --num-callers=200"
    OPTION="$OPTION --show-reachable=yes"
    #OPTION="$OPTION --gen-suppressions=all"
    OPTION="$OPTION --log-file=milk.memcheck.log"
    OPTION="$OPTION --suppressions=$MILK_ROOT/milk.memcheck.supp"
    OPTION="$OPTION --max-stackframe=4442392"

    valgrind ${OPTION} ./milkdebugtest -n ${pname} -f ${fifoname} -s ${SF}
    rm ./milkdebugtest

else

    milk -n ${pname} -f ${fifoname} -s ${SF}

fi

rm ${SF}
