#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions


MSdescr="ImageStreamIO steams control"

# Extended description
MSextdescr="Monitors and controls shared memory data streams
Env variables:

MILK_TUIPRINT_STDIO   use stdio instead of ncurses
MILK_TUIPRINT_NONE    quiet mode - don't print status

"

source milk-script-std-config

# OPTIONS

DEBUG=0
MSopt+=( "D:debug:set_debugmode::set Debug mode" )
function set_debugmode() {
	DEBUG=1
}





RequiredCommands=( milk )
RequiredFiles=()
RequiredDirs=()

source milk-argparse







ttystring=$( tty | tr -d \/ )
pname="streamCTRL"
fifoname="$MILK_SHM_DIR/milkCLIfifo.${pname}.${ttystring}"
SF="$MILK_SHM_DIR/milkCLIstartup.${pname}.${ttystring}"

echo "streamCTRL" > $SF
echo "exitCLI" >> $SF



if [ "$DEBUG" = "1" ]; then

    cp $(which milk) milkdebugtest
    OPTION="--leak-check=full --show-leak-kinds=all"
    OPTION="$OPTION --track-origins=yes"
    OPTION="$OPTION --num-callers=200"
    OPTION="$OPTION --show-reachable=yes"
    #OPTION="$OPTION --gen-suppressions=all"
    OPTION="$OPTION --log-file=milk.memcheck.log"
    OPTION="$OPTION --suppressions=$MILK_ROOT/milk.memcheck.supp"
    OPTION="$OPTION --max-stackframe=4442392"

    valgrind ${OPTION} ./milkdebugtest -n ${pname} -f ${fifoname} -s ${SF}
    rm ./milkdebugtest

else

    MILK_QUIET=1 milk -n ${pname} -f ${fifoname} -s $SF

fi

rm $SF
