#! /bin/bash

# Early-exit help flags
case "${1-}" in
    -h1|--help-oneline) echo "stop logging a shared memory stream"; exit 0 ;;
    -h|--help)
        echo "Usage: milk-logshimoff <stream>  -- stop the log loop"
        exit 0 ;;
esac

EXPECTED_ARGS=1

if [ $# -ne $EXPECTED_ARGS ]
then
    echo
    echo "-------- STOP LOG SHARED MEMORY DATA STREAM ---------"
    echo " "
    echo "Usage: $0 <data stream name>"
    echo " "
    echo "  INPUT <data stream name>   : shared memory stream name. Actual file is $MILK_SHM_DIR/<stream name>.im.shm"
    echo " "
    echo "EXAMPLE :  $0 ircam2"
    echo " "
    exit
fi

pname="$0-$1"
echo "$pname"



milk-streamFITSlog $1 off

exit

milk-cli -n $pname << EOF
shmimslogonset $1 0
exit
EOF
