#! /bin/bash

# Early-exit help flags
case "${1-}" in
    -h1|--help-oneline) echo "kill shared memory log stream process"; exit 0 ;;
    -h|--help)
        echo "Usage: milk-logshimkill <stream>"
        echo "Kill the background process logging a shared memory stream."
        exit 0 ;;
esac


EXPECTED_ARGS=1
if [ $# -ne $EXPECTED_ARGS ]
then
    echo
    echo "-------- KILL LOG SHARED MEMORY DATA STREAM ---------"
    echo " "
    echo "Usage: $0 <data stream name>"
    echo " "
    echo "  INPUT <data stream name>   : shared memory stream name. Actual file is $MILK_SHM_DIR/<stream name>.im.shm"
    echo " "
    echo "EXAMPLE :  $0 ircam2"
    echo " "
    exit
fi

pname="$0-$1"
echo "$pname"



milk-streamFITSlog $1 pstop
sleep 0.5
milk-streamFITSlog $1 kill

exit

milk-cli -n $pname << EOF
shmimslogexitset $1 1
exit
EOF
