#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions


MSdescr="Scan for streams on system"

# Extended description
MSextdescr="Scan for streams
"

source milk-script-std-config


RequiredCommands=( milk )
RequiredFiles=()
RequiredDirs=()

source milk-argparse

fname="_streamscan_$$"
for f in ${MILK_SHM_DIR}/*.im.shm; do
  f1=${f%.im.shm}
  f2=${f1##*/}
  isio-stream-info $f2 2> /dev/null >> $fname
done

column -t $fname
rm $fname

