/**
 * @file    image_arith__im_im__im.c
 * @brief   Binary image×image arithmetic (img,img → img)
 *
 * Applies a binary math function element-wise to two
 * input images, producing an output image.
 *
 * Each operation provides up to four call surfaces,
 * all generated from X-macro tables:
 *
 *  - arith_image_<op>_IMGID(in1, in2, out)
 *    Modern IMGID API.
 *  - arith_image_<op>(name1, name2, name_out)
 *    String-based API for CLI use.
 *  - arith_image_<op>_inplace(name1, name2)
 *    In-place via function-pointer dispatch.
 *  - arith_image_<op>_inplace_byID(ID1, ID2)
 *    In-place via legacy image IDs.
 */


#ifdef MILK_NO_CLI
#include "CLIcore_standalone.h"
#else
#include "libmilkdata/milkdata.h"
#endif

#include "COREMOD_memory/COREMOD_memory.h"

#include "imfunctions.h"
#include "mathfuncs.h"
#include "image_arith__im_im__im.h"


/* ==========================================================
 * X-macro operation tables.
 *
 * BINARY_OPS_FULL — ops with all 4 call surfaces
 *   (IMGID, string, inplace, inplace_byID)
 *
 * BINARY_OPS_NOIP — ops with IMGID + string only
 *   (no inplace variants exist in the public API)
 *
 * Both tables use the same X(op, fptr) shape so they can be
 * expanded by the shared non-inplace generators below.
 *
 * Column: X(op, fptr)
 *   op   — operation suffix
 *   fptr — function-pointer used only for inplace dispatch
 *          generation from BINARY_OPS_FULL; ignored for
 *          BINARY_OPS_NOIP entries
 * ========================================================== */

#define BINARY_OPS_FULL(X) \
    X(fmod,   Pfmod)       \
    X(pow,    Ppow)        \
    X(add,    Padd)        \
    X(sub,    Psub)        \
    X(mult,   Pmult)       \
    X(div,    Pdiv)        \
    X(minv,   Pminv)       \
    X(maxv,   Pmaxv)       \
    X(testlt, Ptestlt)     \
    X(testmt, Ptestmt)

#define BINARY_OPS_NOIP(X) \
    X(teste,  Pteste)      \
    X(testne, Ptestne)     \
    X(testle, Ptestle)     \
    X(testge, Ptestge)     \
    X(and,    Pand)        \
    X(or,     Por)

/** Expand both tables for macros that apply to all */
#define BINARY_OPS_ALL(X) \
    BINARY_OPS_FULL(X)    \
    BINARY_OPS_NOIP(X)


/* ----------------------------------------------------------
 * 1. IMGID wrappers  (img,img → img)
 *
 * Delegates to the optimized, macro-stamped function
 * generated by imfunctions.h.
 * ---------------------------------------------------------- */

#define DEFINE_IMGID(op, fptr) \
int arith_image_##op##_IMGID( \
    IMGID *imgin1,            \
    IMGID *imgin2,            \
    IMGID *imgout)            \
{                             \
    return arith_image_##op##_optimized_IMGID( \
        imgin1, imgin2, imgout);              \
}

BINARY_OPS_ALL(DEFINE_IMGID)
#undef DEFINE_IMGID


/* ----------------------------------------------------------
 * 2. String-based wrappers  (name,name → name)
 *
 * Resolves names to IMGIDs, calls the IMGID variant,
 * and handles output registration and cleanup.
 * ---------------------------------------------------------- */

#define DEFINE_STRING(op, fptr) \
int arith_image_##op(                        \
    const char *ID1_name,                    \
    const char *ID2_name,                    \
    const char *ID_out)                      \
{                                            \
    IMGID imgin1 =                           \
        imgid_make_from_name(ID1_name);      \
    IMGID imgin2 =                           \
        imgid_make_from_name(ID2_name);      \
    IMGID imgout =                           \
        imgid_make_from_name(ID_out);        \
                                             \
    resolveIMGID(&imgin1,                    \
        ERRMODE_ABORT, dcimg, dcnimg);       \
    resolveIMGID(&imgin2,                    \
        ERRMODE_ABORT, dcimg, dcnimg);       \
    resolveIMGID(&imgout,                    \
        ERRMODE_NULL, dcimg, dcnimg);        \
                                             \
    if (imgout.ID == -1) {                   \
        imgout.mdt->shared = dcshareddft;    \
        imgout.mdt->NBkw = NB_KEYWNODE_MAX;  \
    }                                        \
                                             \
    int ret = arith_image_##op##_IMGID(      \
        &imgin1, &imgin2, &imgout);          \
                                             \
    if (imgout.ID == -1                      \
        && imgout.im != NULL) {              \
        RegisterIMGID(                       \
            &imgout, dcimg, dcnimg);         \
    }                                        \
    imgid_free(&imgin1);                     \
    imgid_free(&imgin2);                     \
    imgid_free(&imgout);                     \
    return ret;                              \
}

BINARY_OPS_ALL(DEFINE_STRING)
#undef DEFINE_STRING


/* ----------------------------------------------------------
 * 3. In-place wrappers  (name,name → name1 modified)
 *
 * Uses function-pointer dispatch via
 * arith_image_function_2_1_inplace().
 * Only generated for BINARY_OPS_FULL operations.
 * ---------------------------------------------------------- */

#define DEFINE_INPLACE(op, fptr) \
int arith_image_##op##_inplace(              \
    const char *ID1_name,                    \
    const char *ID2_name)                    \
{                                            \
    arith_image_function_2_1_inplace(        \
        ID1_name, ID2_name, &fptr);          \
    return 0;                                \
}

BINARY_OPS_FULL(DEFINE_INPLACE)
#undef DEFINE_INPLACE


/* ----------------------------------------------------------
 * 4. In-place-by-ID wrappers  (ID,ID → ID1 modified)
 *
 * Legacy API using raw image slot indices.
 * Only generated for BINARY_OPS_FULL operations.
 * ---------------------------------------------------------- */

#define DEFINE_INPLACE_BYID(op, fptr) \
int arith_image_##op##_inplace_byID(         \
    long ID1,                                \
    long ID2)                                \
{                                            \
    arith_image_function_2_1_inplace_byID(   \
        ID1, ID2, &fptr);                    \
    return 0;                                \
}

BINARY_OPS_FULL(DEFINE_INPLACE_BYID)
#undef DEFINE_INPLACE_BYID
