/**
 * @file    image_arith__im_im__im.c
 * @brief   Binary image×image arithmetic (img,img → img)
 *
 * Applies a binary math function element-wise to two
 * input images, producing an output image.
 *
 * Each operation provides up to four call surfaces,
 * all generated from X-macro tables:
 *
 *  - arith_image_<op>_IMGID(in1, in2, out)
 *    Modern IMGID API.
 *  - arith_image_<op>(name1, name2, name_out)
 *    String-based API for CLI use.
 *  - arith_image_<op>_inplace(name1, name2)
 *    In-place via function-pointer dispatch.
 *  - arith_image_<op>_inplace_byID(ID1, ID2)
 *    In-place via legacy image IDs.
 */


#ifdef MILK_NO_CLI
#    include "CLIcore_standalone.h"
#else
#    include "libmilkdata/milkdata.h"
#endif

#include "COREMOD_memory/COREMOD_memory.h"

#include "imfunctions.h"
#include "mathfuncs.h"
#include "image_arith__im_im__im.h"


/* MILK_BINARY_OPS_* tables are defined in image_arith__im_im__im.h */


/* ----------------------------------------------------------
 * 1. IMGID wrappers  (img,img → img)
 *
 * Delegates to the optimized, macro-stamped function
 * generated by imfunctions.h.
 * ---------------------------------------------------------- */

#define DEFINE_IMGID(op, fptr)                                                \
    int arith_image_##op##_IMGID(IMGID *imgin1, IMGID *imgin2, IMGID *imgout) \
    {                                                                         \
        return arith_image_##op##_optimized_IMGID(imgin1, imgin2, imgout);    \
    }

MILK_BINARY_OPS_ALL(DEFINE_IMGID)
#undef DEFINE_IMGID


/* ----------------------------------------------------------
 * 2. String-based wrappers  (name,name → name)
 *
 * Resolves names to IMGIDs, calls the IMGID variant,
 * and handles output registration and cleanup.
 * ---------------------------------------------------------- */

#define DEFINE_STRING(op, fptr)                                                          \
    int arith_image_##op(const char *ID1_name, const char *ID2_name, const char *ID_out) \
    {                                                                                    \
        IMGID imgin1 = imgid_make_from_name(ID1_name);                                   \
        IMGID imgin2 = imgid_make_from_name(ID2_name);                                   \
        IMGID imgout = imgid_make_from_name(ID_out);                                     \
                                                                                         \
        resolveIMGID(&imgin1, ERRMODE_ABORT, dcimg, dcnimg);                             \
        resolveIMGID(&imgin2, ERRMODE_ABORT, dcimg, dcnimg);                             \
        resolveIMGID(&imgout, ERRMODE_NULL, dcimg, dcnimg);                              \
                                                                                         \
        if (imgout.ID == -1)                                                             \
        {                                                                                \
            imgout.mdt->shared = dcshareddft;                                            \
            imgout.mdt->NBkw   = NB_KEYWNODE_MAX;                                        \
        }                                                                                \
                                                                                         \
        int ret = arith_image_##op##_IMGID(&imgin1, &imgin2, &imgout);                   \
                                                                                         \
        if (imgout.ID == -1 && imgout.im != NULL)                                        \
        {                                                                                \
            RegisterIMGID(&imgout, dcimg, dcnimg);                                       \
        }                                                                                \
        imgid_free(&imgin1);                                                             \
        imgid_free(&imgin2);                                                             \
        imgid_free(&imgout);                                                             \
        return ret;                                                                      \
    }

MILK_BINARY_OPS_ALL(DEFINE_STRING)
#undef DEFINE_STRING


/* ----------------------------------------------------------
 * 3. In-place wrappers  (name,name → name1 modified)
 *
 * Uses function-pointer dispatch via
 * arith_image_function_2_1_inplace().
 * Only generated for MILK_BINARY_OPS_FULL operations.
 * ---------------------------------------------------------- */

#define DEFINE_INPLACE(op, fptr)                                               \
    int arith_image_##op##_inplace(const char *ID1_name, const char *ID2_name) \
    {                                                                          \
        arith_image_function_2_1_inplace(ID1_name, ID2_name, &fptr);           \
        return 0;                                                              \
    }

MILK_BINARY_OPS_FULL(DEFINE_INPLACE)
#undef DEFINE_INPLACE


/* ----------------------------------------------------------
 * 4. In-place-by-ID wrappers  (ID,ID → ID1 modified)
 *
 * Legacy API using raw image slot indices.
 * Only generated for MILK_BINARY_OPS_FULL operations.
 * ---------------------------------------------------------- */
