/**
 * @file    imfunctions.c
 * @brief   Per-pixel function dispatch for image arith
 *
 * Central dispatch engine for applying scalar math
 * functions to image pixels. Contains generic
 * function-pointer variants and macro-stamped
 * optimized variants for common operations.
 *
 * Architecture:
 *  - Generic variants accept a function pointer and
 *    loop over all datatypes via else-if chains.
 *  - Optimized variants (generated by
 *    STAMP_BINARY_2_1 / STAMP_BINARY_1F_1 /
 *    STAMP_UNARY_1_1 macros) inline the operation
 *    for SIMD vectorization.
 *
 * Naming convention:
 *  - arith_image_function_im_im__d_d   — unary
 *    (image → image).
 *  - arith_image_function_imd_im__dd_d — image +
 *    scalar → image.
 *  - arith_image_function_imim_im__dd_d — image +
 *    image → image.
 *  - _IMGID suffix = modern IMGID API.

 *  - _inplace suffix = result overwrites input.
 */


#include <math.h>

#ifdef MILK_NO_CLI
#include "CLIcore_standalone.h"
#else
#include "libmilkdata/milkdata.h"
#include "milkDebugTools.h"
#endif

#include "libmilkcommon/milk_compiler.h"
#include "COREMOD_memory/COREMOD_memory.h"
#include "imfunctions.h"

// Suppress -Wunknown-pragmas for _Pragma("omp ...") expansions
// when OpenMP is globally disabled in the build.
#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#endif

#include "image_arith__im_f__im.h"
#include "imgid_arith_helpers.h"
#include <libmilkdata/milk_type_dispatch.h>
#include "mathfuncs.h"

#ifdef _OPENMP
#include <omp.h>
#define OMP_NELEMENT_LIMIT 100000
#define OMP_FOR_SIMD _Pragma("omp for simd")
#else
#define OMP_FOR_SIMD
#endif

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif

#define RESOLVE_CALL_CLEANUP(ID_in, ID_out, CALL_EXPR) \
do { \
    IMGID _in  = imgid_make_from_name(ID_in); \
    IMGID _out = imgid_make_from_name(ID_out); \
    resolveIMGID(&_in, ERRMODE_WARN, dcimg, dcnimg); \
    resolveIMGID(&_out, ERRMODE_NULL, dcimg, dcnimg); \
    if (_in.ID == -1) { \
        return RETURN_FAILURE; \
    } \
    if (_out.ID == -1) { \
        _out.mdt->shared = dcshareddft; \
        _out.mdt->NBkw = NB_KEYWNODE_MAX; \
    } \
    errno_t _ret = (CALL_EXPR); \
    if (_out.ID == -1 && _out.im != NULL) { \
        RegisterIMGID(&_out, dcimg, dcnimg); \
    } \
    imgid_free(&_in); \
    imgid_free(&_out); \
    return _ret; \
} while (0)

/**
 * @brief Read any-type pixel as double
 *
 * Runtime datatype dispatch for a single pixel.
 * Used by generic (non-stamped) dispatch paths.
 *
 * @param im     Image pointer
 * @param index  Pixel index
 * @return Pixel value cast to double
 */
static inline double get_pixel_double(
    IMAGE    *im,
    uint64_t index)
{
    switch(im->md[0].datatype)
    {
    case _DATATYPE_UINT8: return (double)im->array.UI8[index];
    case _DATATYPE_INT8: return (double)im->array.SI8[index];
    case _DATATYPE_UINT16: return (double)im->array.UI16[index];
    case _DATATYPE_INT16: return (double)im->array.SI16[index];
    case _DATATYPE_UINT32: return (double)im->array.UI32[index];
    case _DATATYPE_INT32: return (double)im->array.SI32[index];
    case _DATATYPE_UINT64: return (double)im->array.UI64[index];
    case _DATATYPE_INT64: return (double)im->array.SI64[index];
    case _DATATYPE_FLOAT: return (double)im->array.F[index];
    case _DATATYPE_DOUBLE: return (double)im->array.D[index];
    default: return 0.0;
    }
}

static inline void do_math_2_1_fastpath(
    IMGID                         *inimg1,
    IMGID                         *inimg2,
    IMGID                         *outimg,
    double (*pt2function)(double, double))
{
    uint64_t nelement = inimg1->md->nelement;
    uint8_t datatype = outimg->mdt->datatype;
    uint8_t datatype1 = inimg1->md->datatype;
    uint8_t datatype2 = inimg2->md->datatype;

#ifdef _OPENMP
    #pragma omp parallel if (nelement > OMP_NELEMENT_LIMIT)
    {
#endif
        if(datatype == _DATATYPE_FLOAT && datatype1 == _DATATYPE_FLOAT && datatype2 == _DATATYPE_FLOAT)
        {
            float *MILK_RESTRICT outptr = MILK_ASSUME_ALIGNED(outimg->im->array.F);
            const float *MILK_RESTRICT in1ptr = MILK_ASSUME_ALIGNED(inimg1->im->array.F);
            const float *MILK_RESTRICT in2ptr = MILK_ASSUME_ALIGNED(inimg2->im->array.F);
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(uint64_t ii = 0; ii < nelement; ii++)
            {
                outptr[ii] = (float)pt2function((double)in1ptr[ii], (double)in2ptr[ii]);
            }
        }
        else if(datatype == _DATATYPE_DOUBLE && datatype1 == _DATATYPE_DOUBLE
                && datatype2 == _DATATYPE_DOUBLE)
        {
            double *MILK_RESTRICT outptr = MILK_ASSUME_ALIGNED(outimg->im->array.D);
            const double *MILK_RESTRICT in1ptr = MILK_ASSUME_ALIGNED(inimg1->im->array.D);
            const double *MILK_RESTRICT in2ptr = MILK_ASSUME_ALIGNED(inimg2->im->array.D);
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(uint64_t ii = 0; ii < nelement; ii++)
            {
                outptr[ii] = pt2function(in1ptr[ii], in2ptr[ii]);
            }
        }
        else if(datatype == _DATATYPE_FLOAT)
        {
            float *MILK_RESTRICT outptr = MILK_ASSUME_ALIGNED(outimg->im->array.F);
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(uint64_t ii = 0; ii < nelement; ii++)
            {
                double v1 = (datatype1 == _DATATYPE_DOUBLE) ? inimg1->im->array.D[ii] :
                            (datatype1 == _DATATYPE_FLOAT) ? inimg1->im->array.F[ii] :
                            get_pixel_double(inimg1->im, ii);
                double v2 = (datatype2 == _DATATYPE_DOUBLE) ? inimg2->im->array.D[ii] :
                            (datatype2 == _DATATYPE_FLOAT) ? inimg2->im->array.F[ii] :
                            get_pixel_double(inimg2->im, ii);
                outptr[ii] = (float)pt2function(v1, v2);
            }
        }
        else if(datatype == _DATATYPE_DOUBLE)
        {
            double *MILK_RESTRICT outptr = MILK_ASSUME_ALIGNED(outimg->im->array.D);
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(uint64_t ii = 0; ii < nelement; ii++)
            {
                double v1 = (datatype1 == _DATATYPE_DOUBLE) ? inimg1->im->array.D[ii] :
                            (datatype1 == _DATATYPE_FLOAT) ? inimg1->im->array.F[ii] :
                            get_pixel_double(inimg1->im, ii);
                double v2 = (datatype2 == _DATATYPE_DOUBLE) ? inimg2->im->array.D[ii] :
                            (datatype2 == _DATATYPE_FLOAT) ? inimg2->im->array.F[ii] :
                            get_pixel_double(inimg2->im, ii);
                outptr[ii] = pt2function(v1, v2);
            }
        }
#ifdef _OPENMP
    }
#endif
}

/* ------------------------------------------------------------------------- */
/* Functions for bison / flex                                                */
/* im : image
  d : double

  function_<inputformat>_<outputformat>__<math function input>_<math function output>

  examples:
  function_imim__dd_d  : input is (image, image), applies double,double -> double function

  ------------------------------------------------------------------------- */

/**
 * @brief Apply unary function to image (IMGID API)
 *
 * For each pixel: out[i] = func( (double)in[i] ).
 * Output inherits input dimensions; output type is
 * FLOAT unless input is DOUBLE.
 *
 * @param imgin        Input image
 * @param imgout       Output image (created if NULL)
 * @param pt2function  Scalar function double→double
 * @return RETURN_SUCCESS or RETURN_FAILURE
 */
errno_t arith_image_function_im_im__d_d_IMGID(
    IMGID *imgin,
    IMGID *imgout,
    double (*pt2function)(double))
{
    if(imgin->im == NULL)
    {
        return RETURN_FAILURE;
    }

    DEBUG_TRACEPOINT("arith_image_function_d_d  %s %s\n", imgin->name, imgout->name);

    imgout->mdt->naxis = imgin->md->naxis;
    for(uint8_t i = 0; i < imgin->md->naxis; i++)
    {
        imgout->mdt->size[i] = imgin->md->size[i];
    }

    imgout->mdt->datatype = _DATATYPE_FLOAT;
    if(imgin->md->datatype == _DATATYPE_DOUBLE)
    {
        imgout->mdt->datatype = _DATATYPE_DOUBLE;
    }

    if(imgout->im == NULL)
    {
        imgout->im = (IMAGE *) calloc(1, sizeof(IMAGE));
    }
    else
    {
        if(imgout->im->md && imgout->im->md->shared == 1)
        {
            ImageStreamIO_closeIm(imgout->im);
        }
        else
        {
            ImageStreamIO_destroyIm(imgout->im);
        }
    }
    imgid_mkimage(imgout);

    uint64_t nelement = imgin->md->nelement;
    uint8_t  datatype = imgin->md->datatype;

#ifdef _OPENMP
    #pragma omp parallel if (nelement > OMP_NELEMENT_LIMIT)
    {
#endif

#define UNARY_BODY(M)                                 \
    OMP_FOR_SIMD                                      \
    for (uint64_t ii = 0; ii < nelement; ii++)        \
    {                                                 \
        imgout->im->array.F[ii] =                     \
            (float) pt2function(                      \
                (double)(imgin->im->array.M[ii]));    \
    }

#define UNARY_BODY_D                                  \
    OMP_FOR_SIMD                                      \
    for (uint64_t ii = 0; ii < nelement; ii++)        \
    {                                                 \
        imgout->im->array.D[ii] =                     \
            pt2function(imgin->im->array.D[ii]);      \
    }

        MILK_FOR_EACH_DATATYPE(datatype, UNARY_BODY, UNARY_BODY_D)

#undef UNARY_BODY
#undef UNARY_BODY_D

#ifdef _OPENMP
    }
#endif

    DEBUG_TRACEPOINT("arith_image_function_d_d  DONE\n");

    return RETURN_SUCCESS;
}

/**
 * @brief Apply unary function to image (string API)
 *
 * Resolves image names to IMGIDs, then delegates
 * to the _IMGID variant.
 *
 * @param ID_name       Input image name
 * @param ID_out        Output image name
 * @param pt2function   Scalar function
 * @return RETURN_SUCCESS or RETURN_FAILURE
 */
errno_t arith_image_function_im_im__d_d(
    const char *__restrict ID_name,
    const char *__restrict ID_out,
    double (*pt2function)(double))
{
    RESOLVE_CALL_CLEANUP(ID_name, ID_out,
                         arith_image_function_im_im__d_d_IMGID(&_in, &_out, pt2function));
}

/**
 * @brief Apply image+scalar function (IMGID API)
 *
 * For each pixel: out[i] = func( (double)in[i], v0 ).
 *
 * @param imgin        Input image
 * @param v0           Scalar constant
 * @param imgout       Output image
 * @param pt2function  Binary function (double,double)
 * @return RETURN_SUCCESS or RETURN_FAILURE
 */
errno_t arith_image_function_imd_im__dd_d_IMGID(
    IMGID                         *imgin,
    double                        v0,
    IMGID                         *imgout,
    double (*pt2function)(double, double))
{

    if(imgin->im == NULL)
    {
        return RETURN_FAILURE;
    }

    imgout->mdt->naxis = imgin->md->naxis;
    for(uint8_t i = 0; i < imgin->md->naxis; i++)
    {
        imgout->mdt->size[i] = imgin->md->size[i];
    }

    imgout->mdt->datatype = _DATATYPE_FLOAT;
    if(imgin->md->datatype == _DATATYPE_DOUBLE)
    {
        imgout->mdt->datatype = _DATATYPE_DOUBLE;
    }

    if(imgout->im == NULL)
    {
        imgout->im = (IMAGE *) calloc(1, sizeof(IMAGE));
    }
    else
    {
        if(imgout->im->md && imgout->im->md->shared == 1)
        {
            ImageStreamIO_closeIm(imgout->im);
        }
        else
        {
            ImageStreamIO_destroyIm(imgout->im);
        }
    }
    imgid_mkimage(imgout);

    uint64_t nelement = imgin->md->nelement;
    uint8_t  datatype = imgin->md->datatype;

#ifdef _OPENMP
    #pragma omp parallel if (nelement > OMP_NELEMENT_LIMIT)
    {
#endif

#define CST1_BODY(M)                                  \
    OMP_FOR_SIMD                                      \
    for (uint64_t ii = 0; ii < nelement; ii++)        \
    {                                                 \
        imgout->im->array.F[ii] =                     \
            (float) pt2function(                      \
                (double)(imgin->im->array.M[ii]),     \
                v0);                                  \
    }

#define CST1_BODY_D                                   \
    OMP_FOR_SIMD                                      \
    for (uint64_t ii = 0; ii < nelement; ii++)        \
    {                                                 \
        imgout->im->array.D[ii] =                     \
            pt2function(imgin->im->array.D[ii], v0);  \
    }

        MILK_FOR_EACH_DATATYPE(datatype, CST1_BODY, CST1_BODY_D)

#undef CST1_BODY
#undef CST1_BODY_D

#ifdef _OPENMP
    }
#endif

    DEBUG_TRACEPOINT("arith_image_function_d_d  DONE\n");

    return RETURN_SUCCESS;
}

/**
 * @brief Apply image+scalar function (string API)
 *
 * @param ID_name       Input image name
 * @param v0            Scalar constant
 * @param ID_out        Output image name
 * @param pt2function   Binary function
 * @return RETURN_SUCCESS or RETURN_FAILURE
 */
errno_t arith_image_function_imd_im__dd_d(
    const char *__restrict        ID_name,
    double                        v0,
    const char *__restrict        ID_out,
    double (*pt2function)(double, double))
{
    RESOLVE_CALL_CLEANUP(ID_name, ID_out,
                         arith_image_function_imd_im__dd_d_IMGID(&_in, v0, &_out, pt2function));
}

/**
 * @brief Apply image+2-scalar function (IMGID API)
 *
 * For each pixel: out[i] = func(in[i], v0, v1).
 * Used for Ptrunc (clamp to [v0, v1]).
 *
 * @param imgin        Input image
 * @param v0           First scalar
 * @param v1           Second scalar
 * @param imgout       Output image
 * @param pt2function  Ternary function
 * @return RETURN_SUCCESS or RETURN_FAILURE
 */
errno_t arith_image_function_imdd_im__ddd_d_IMGID(
    IMGID                         *imgin,
    double                        v0,
    double                        v1,
    IMGID                         *imgout,
    double (*pt2function)(double, double, double))
{

    if(imgin->im == NULL)
    {
        return RETURN_FAILURE;
    }

    imgout->mdt->naxis = imgin->md->naxis;
    for(uint8_t i = 0; i < imgin->md->naxis; i++)
    {
        imgout->mdt->size[i] = imgin->md->size[i];
    }

    imgout->mdt->datatype = _DATATYPE_FLOAT;
    if(imgin->md->datatype == _DATATYPE_DOUBLE)
    {
        imgout->mdt->datatype = _DATATYPE_DOUBLE;
    }

    if(imgout->im == NULL)
    {
        imgout->im = (IMAGE *) calloc(1, sizeof(IMAGE));
    }
    else
    {
        if(imgout->im->md && imgout->im->md->shared == 1)
        {
            ImageStreamIO_closeIm(imgout->im);
        }
        else
        {
            ImageStreamIO_destroyIm(imgout->im);
        }
    }
    imgid_mkimage(imgout);

    uint64_t nelement = imgin->md->nelement;
    uint8_t  datatype = imgin->md->datatype;

#ifdef _OPENMP
    #pragma omp parallel if (nelement > OMP_NELEMENT_LIMIT)
    {
#endif

#define CST2_BODY(M)                                  \
    OMP_FOR_SIMD                                      \
    for (uint64_t _ii = 0; _ii < nelement; _ii++)     \
    {                                                 \
        imgout->im->array.F[_ii] =                    \
            (float) pt2function(                      \
                (double)(imgin->im->array.M[_ii]),    \
                v0, v1);                              \
    }

#define CST2_BODY_D                                   \
    OMP_FOR_SIMD                                      \
    for (uint64_t _ii = 0; _ii < nelement; _ii++)     \
    {                                                 \
        imgout->im->array.D[_ii] =                    \
            pt2function(                              \
                imgin->im->array.D[_ii], v0, v1);     \
    }

        MILK_FOR_EACH_DATATYPE(datatype, CST2_BODY, CST2_BODY_D)

#undef CST2_BODY
#undef CST2_BODY_D

#ifdef _OPENMP
    }
#endif

    DEBUG_TRACEPOINT("arith_image_function_d_d  DONE\n");

    return RETURN_SUCCESS;
}

/**
 * @brief Apply image+2-scalar function (string API)
 */
errno_t arith_image_function_imdd_im__ddd_d(
    const char                    *ID_name,
    double                        v0,
    double                        v1,
    const char                    *ID_out,
    double (*pt2function)(double, double, double))
{
    RESOLVE_CALL_CLEANUP(ID_name, ID_out,
                         arith_image_function_imdd_im__ddd_d_IMGID(&_in, v0, v1, &_out, pt2function));

}



errno_t arith_image_function_1_1_IMGID(
    IMGID *imgin,
    IMGID *imgout,
    double (*pt2function)(double))
{
    return arith_image_function_im_im__d_d_IMGID(imgin, imgout, pt2function);
}

/**
 * @brief Apply a unary function to an image.
 *
 * Creates a new output image with the given
 * function applied element-wise (e.g. cos, asin).
 */
errno_t arith_image_function_1_1(
    const char *ID_name,
    const char *ID_out,
    double (*pt2function)(double))
{
    return arith_image_function_im_im__d_d(ID_name, ID_out, pt2function);
}

// imagein -> imagein (in place)
errno_t arith_image_function_1_1_inplace_IMGID(
    IMGID *imgin,
    double (*pt2function)(double))
{
    uint8_t datatype = imgin->im->md->datatype;
    uint64_t nelement = imgin->im->md->nelement;

    imgin->im->md->write = 0;
#ifdef _OPENMP
    #pragma omp parallel if (nelement > OMP_NELEMENT_LIMIT)
    {
#endif

#define INPLACE_BODY(M)                               \
    OMP_FOR_SIMD                                      \
    for (uint64_t _ii = 0; _ii < nelement; _ii++)     \
    {                                                 \
        imgin->im->array.F[_ii] =                     \
            pt2function(                              \
                (double)(imgin->im->array.M[_ii]));   \
    }

#define INPLACE_BODY_D                                \
    OMP_FOR_SIMD                                      \
    for (uint64_t _ii = 0; _ii < nelement; _ii++)     \
    {                                                 \
        imgin->im->array.D[_ii] =                     \
            (double) pt2function(                     \
                (double)(imgin->im->array.D[_ii]));   \
    }

        MILK_FOR_EACH_DATATYPE(datatype,
                               INPLACE_BODY, INPLACE_BODY_D)

#undef INPLACE_BODY
#undef INPLACE_BODY_D

#ifdef _OPENMP
    }
#endif

    imgin->im->md->write = 0;
    imgin->im->md->cnt0++;

    return RETURN_SUCCESS;
}

// imagein -> imagein (in place)
errno_t arith_image_function_1_1_inplace(
    const char *ID_name,
    double (*pt2function)(double))
{
    IMGID img = imgid_make_from_name(ID_name);
    resolveIMGID(&img, ERRMODE_WARN, dcimg, dcnimg);
    errno_t ret = arith_image_function_1_1_inplace_IMGID(&img, pt2function);
    if(img.ID == -1)
    {
        return RETURN_FAILURE;
    }
    imgid_free(&img);
    return ret;
}

/* ------------------------------------------------------------------------- */
/* image, image  -> image                                                    */
/* ------------------------------------------------------------------------- */

errno_t arith_image_function_2_1_IMGID(
    IMGID                         *inimg1,
    IMGID                         *inimg2,
    IMGID                         *outimg,
    double (*pt2function)(double, double))
{
    DEBUG_TRACE_FSTART();

    if(inimg1->im == NULL || inimg2->im == NULL)
    {
        return RETURN_FAILURE;
    }

    if(outimg->im == NULL)
    {
        imgid_copy(inimg1, outimg);
    }

    // output naxis is max of inputs
    outimg->mdt->naxis = inimg1->md->naxis;
    if(inimg2->md->naxis > inimg1->md->naxis)
    {
        outimg->mdt->naxis = inimg2->md->naxis;
    }

    // axis expansion flags
    int in1expand[3];
    int in2expand[3];

    // check which coordinate needs to be expanded in computation
    //
    uint64_t nbpix = 1;
    uint64_t nbpix1 = 1;
    uint64_t nbpix2 = 1;
    for(uint8_t axis = 0; axis < outimg->mdt->naxis; axis++)
    {
        in1expand[axis] = 1;
        in2expand[axis] = 1;

        uint32_t size1;
        if(axis < inimg1->md->naxis)
        {
            size1 = inimg1->md->size[axis];
        }
        else
        {
            size1 = 1;
        }
        nbpix1 *= size1;

        uint32_t size2;
        if(axis < inimg2->md->naxis)
        {
            size2 = inimg2->md->size[axis];
        }
        else
        {
            size2 = 1;
        }
        nbpix2 *= size2;

        if(size1 != size2)
        {
            if(size1 == 1)
            {
                in1expand[axis] = 0;
                outimg->mdt->size[axis] = size2;

            }
            else if(size2 == 1)
            {
                in2expand[axis] = 0;
                outimg->mdt->size[axis] = size1;
            }
            else
            {
                PRINT_ERROR("axis %d size %u and %u incompatible", axis, size1, size2);
                abort();
            }
        }
        nbpix *= outimg->mdt->size[axis];
    }
    for(uint8_t axis = outimg->mdt->naxis; axis < 3; axis++)
    {
        outimg->mdt->size[axis] = 1;
        in1expand[axis] = 1;
        in2expand[axis] = 1;
    }

    outimg->mdt->datatype = _DATATYPE_FLOAT; // default
    if(inimg1->md->datatype == _DATATYPE_DOUBLE)
    {
        outimg->mdt->datatype = _DATATYPE_DOUBLE;
    }
    if(inimg2->md->datatype == _DATATYPE_DOUBLE)
    {
        outimg->mdt->datatype = _DATATYPE_DOUBLE;
    }

    if(outimg->im == NULL)
    {
        outimg->im = (IMAGE *) calloc(1, sizeof(IMAGE));
    }
    else
    {
        ImageStreamIO_closeIm(outimg->im);
    }
    imgid_mkimage(outimg);

    // Metadata caching
    uint64_t nelement = outimg->md->nelement;
    uint8_t datatype = outimg->mdt->datatype;
    uint8_t datatype1 = inimg1->md->datatype;
    uint8_t datatype2 = inimg2->md->datatype;

    // Fast path: images have same size and layout
    int fastpath = 1;
    if(inimg1->md->naxis != inimg2->md->naxis)
    {
        fastpath = 0;
    }
    else
    {
        for(uint8_t axis = 0; axis < outimg->mdt->naxis; axis++)
        {
            if(inimg1->md->size[axis] != inimg2->md->size[axis])
            {
                fastpath = 0;
                break;
            }
        }
    }

    if(fastpath)
    {
        do_math_2_1_fastpath(inimg1, inimg2, outimg, pt2function);
        DEBUG_TRACE_FEXIT();
        return RETURN_SUCCESS;
    }


    // slow path with broadcasting
    uint64_t *__restrict inpix1 = (uint64_t *) malloc(sizeof(uint64_t) * nbpix);
    uint64_t *__restrict inpix2 = (uint64_t *) malloc(sizeof(uint64_t) * nbpix);

    for(uint32_t ii = 0; ii < outimg->mdt->size[0]; ii++)
    {
        uint32_t ii1 = ii * in1expand[0];
        uint32_t ii2 = ii * in2expand[0];

        for(uint32_t jj = 0; jj < outimg->mdt->size[1]; jj++)
        {
            uint32_t jj1 = jj * in1expand[1];
            uint32_t jj2 = jj * in2expand[1];

            for(uint32_t kk = 0; kk < outimg->mdt->size[2]; kk++)
            {
                uint64_t outpixi = ii;
                outpixi +=  jj * outimg->mdt->size[0];
                outpixi +=  kk * outimg->mdt->size[1] * outimg->mdt->size[0];

                uint32_t kk1 = kk * in1expand[2];
                uint32_t kk2 = kk * in2expand[2];

                inpix1[outpixi] =  kk1 * inimg1->md->size[1] * inimg1->md->size[0] + jj1 * inimg1->md->size[0] +
                                   ii1;
                inpix2[outpixi] =  kk2 * inimg2->md->size[1] * inimg2->md->size[0] + jj2 * inimg2->md->size[0] +
                                   ii2;
            }
        }
    }

    double *ptr1array;
    int ptr1allocate = 0;
    if(inimg1->md->datatype == _DATATYPE_DOUBLE)
    {
        ptr1array = inimg1->im->array.D;
    }
    else
    {
        ptr1allocate = 1;
        ptr1array = (double *) malloc(sizeof(double) * nbpix1);
        for(uint64_t ii = 0; ii < nbpix1; ii++) ptr1array[ii] = get_pixel_double(inimg1->im, ii);
    }

    double *ptr2array;
    int ptr2allocate = 0;
    if(inimg2->md->datatype == _DATATYPE_DOUBLE)
    {
        ptr2array = inimg2->im->array.D;
    }
    else
    {
        ptr2allocate = 1;
        ptr2array = (double *) malloc(sizeof(double) * nbpix2);
        for(uint64_t ii = 0; ii < nbpix2; ii++) ptr2array[ii] = get_pixel_double(inimg2->im, ii);
    }

    if(outimg->mdt->datatype == _DATATYPE_FLOAT)
    {
        for(uint64_t ii = 0; ii < nbpix;
            ii++) outimg->im->array.F[ii] = (float)pt2function(ptr1array[inpix1[ii]],
                                                ptr2array[inpix2[ii]]);
    }
    else if(outimg->mdt->datatype == _DATATYPE_DOUBLE)
    {
        for(
            uint64_t ii = 0; ii < nbpix; ii++) outimg->im->array.D[ii] = pt2function(ptr1array[inpix1[ii]],
                        ptr2array[inpix2[ii]]);
    }

    if(ptr1allocate == 1)
    {
        free(ptr1array);
    }
    if(ptr2allocate == 1)
    {
        free(ptr2array);
    }
    free(inpix1);
    free(inpix2);

    DEBUG_TRACE_FEXIT();
    return RETURN_SUCCESS;
}

errno_t arith_img_function_2_1(
    IMGID                         inimg1,
    IMGID                         inimg2,
    IMGID                         *outimg,
    double (*pt2function)(double, double))
{
    return arith_image_function_2_1_IMGID(&inimg1, &inimg2, outimg, pt2function);
}

/* ------------------------------------------------------------------------- */
/* image, image  -> image                                                    */
/* ------------------------------------------------------------------------- */

errno_t arith_image_function_2_1(
    const char                    *ID_name1,
    const char                    *ID_name2,
    const char                    *ID_out,
    double (*pt2function)(double, double))
{
    IMGID inimg1 = imgid_make_from_name(ID_name1);
    IMGID inimg2 = imgid_make_from_name(ID_name2);
    IMGID outimg = imgid_make_from_name(ID_out);

    resolveIMGID(&inimg1, ERRMODE_WARN, dcimg, dcnimg);
    resolveIMGID(&inimg2, ERRMODE_WARN, dcimg, dcnimg);
    if(inimg1.ID == -1)
    {
        return RETURN_FAILURE;
    }
    if(inimg2.ID == -1)
    {
        return RETURN_FAILURE;
    }
    resolveIMGID(&outimg, ERRMODE_NULL, dcimg, dcnimg);

    if(outimg.ID == -1)
    {
        outimg.mdt->shared = dcshareddft;
        outimg.mdt->NBkw = NB_KEYWNODE_MAX;
    }

    errno_t ret = arith_image_function_2_1_IMGID(&inimg1, &inimg2, &outimg, pt2function);

    if(outimg.ID == -1 && outimg.im != NULL)
    {
        RegisterIMGID(&outimg, dcimg, dcnimg);
    }
    imgid_free(&inimg1);
    imgid_free(&inimg2);
    imgid_free(&outimg);
    return ret;
}

errno_t arith_image_function_2_1_inplace(
    const char                    *ID_name1,
    const char                    *ID_name2,
    double (*pt2function)(double, double))
{
    IMGID img1 = imgid_make_from_name(ID_name1);
    IMGID img2 = imgid_make_from_name(ID_name2);

    resolveIMGID(&img1, ERRMODE_ABORT, dcimg, dcnimg);
    resolveIMGID(&img2, ERRMODE_ABORT, dcimg, dcnimg);

    if(img1.im == NULL || img2.im == NULL)
    {
        imgid_free(&img1);
        imgid_free(&img2);
        return RETURN_FAILURE;
    }

    long nelement = img1.md->nelement;
    if(nelement != img2.md->nelement)
    {
        PRINT_ERROR("images %s and %s have different nelement\n", ID_name1, ID_name2);
        imgid_free(&img1);
        imgid_free(&img2);
        return RETURN_FAILURE;
    }

    uint8_t dt1 = img1.md->datatype;
    img1.im->md->write = 1;

#ifdef _OPENMP
    #pragma omp parallel if (nelement > OMP_NELEMENT_LIMIT)
    {
        #pragma omp for simd
#endif
        for(uint64_t ii = 0; ii < nelement; ii++)
        {
            double v1 = get_pixel_double(img1.im, ii);
            double v2 = get_pixel_double(img2.im, ii);
            if(dt1 == _DATATYPE_FLOAT)
            {
                img1.im->array.F[ii] = (float) pt2function(v1, v2);
            }
            else if(dt1 == _DATATYPE_DOUBLE)
            {
                img1.im->array.D[ii] = pt2function(v1, v2);
            }
        }
#ifdef _OPENMP
    }
#endif

    img1.im->md->write = 0;
    img1.im->md->cnt0++;

    imgid_free(&img1);
    imgid_free(&img2);

    return RETURN_SUCCESS;
}

/* ------------------------------------------------------------------------- */
/* complex image, complex image  -> complex image                            */
/* ------------------------------------------------------------------------- */
// Migrated to im_complex.c

int arith_image_function_1f_1_IMGID(
    IMGID                         *imgin,
    double                        f1,
    IMGID                         *imgout,
    double (*pt2function)(double, double))
{
    if(imgin->im == NULL)
    {
        return RETURN_FAILURE;
    }

    imgout->mdt->naxis = imgin->md->naxis;
    for(uint8_t i = 0; i < imgin->md->naxis; i++)
    {
        imgout->mdt->size[i] = imgin->md->size[i];
    }
    imgout->mdt->datatype = (imgin->md->datatype == _DATATYPE_DOUBLE) ? _DATATYPE_DOUBLE :
                            _DATATYPE_FLOAT;

    if(imgout->im == NULL)
    {
        imgout->im = (IMAGE *) calloc(1, sizeof(IMAGE));
    }
    else
    {
        if(imgout->im->md && imgout->im->md->shared == 1)
        {
            ImageStreamIO_closeIm(imgout->im);
        }
        else
        {
            ImageStreamIO_destroyIm(imgout->im);
        }
    }
    imgid_mkimage(imgout);

    uint64_t nelement = imgin->md->nelement;

    if(imgin->md->datatype == _DATATYPE_FLOAT && imgout->mdt->datatype == _DATATYPE_FLOAT)
    {
        float *restrict ptr = imgin->im->array.F;
        float *out = imgout->im->array.F;
#ifdef _OPENMP
        #pragma omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)
#endif
        for(uint64_t ii = 0; ii < nelement; ii++)
        {
            out[ii] = (float)pt2function((double)ptr[ii], f1);
        }
    }
    else if(imgin->md->datatype == _DATATYPE_DOUBLE && imgout->mdt->datatype == _DATATYPE_DOUBLE)
    {
        double *restrict ptr = imgin->im->array.D;
        double *out = imgout->im->array.D;
#ifdef _OPENMP
        #pragma omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)
#endif
        for(uint64_t ii = 0; ii < nelement; ii++)
        {
            out[ii] = pt2function(ptr[ii], f1);
        }
    }
    else
    {
#ifdef _OPENMP
        #pragma omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)
#endif
        for(uint64_t ii = 0; ii < nelement; ii++)
        {
            double v = get_pixel_double(imgin->im, ii);
            if(imgout->mdt->datatype == _DATATYPE_FLOAT)
            {
                imgout->im->array.F[ii] = (float)pt2function(v, f1);
            }
            else
            {
                imgout->im->array.D[ii] = pt2function(v, f1);
            }
        }
    }
    return EXIT_SUCCESS;
}

int arith_image_function_1f_1(
    const char                    *ID_name,
    double                        f1,
    const char                    *ID_out,
    double (*pt2function)(double, double))
{
    RESOLVE_CALL_CLEANUP(ID_name, ID_out,
                         arith_image_function_1f_1_IMGID(&_in, f1, &_out, pt2function));

}

int arith_image_function_1f_1_inplace_IMGID(
    IMGID                         *imgin,
    double                        f1,
    double (*pt2function)(double, double))
{
    uint64_t nelement = imgin->im->md[0].nelement;
#ifdef _OPENMP
    #pragma omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)
#endif
    for(uint64_t ii = 0; ii < nelement; ii++)
    {
        double v = get_pixel_double(imgin->im, ii);
        if(imgin->im->md[0].datatype == _DATATYPE_FLOAT)
        {
            imgin->im->array.F[ii] = (float)pt2function(v, f1);
        }
        else if(imgin->im->md[0].datatype == _DATATYPE_DOUBLE)
        {
            imgin->im->array.D[ii] = pt2function(v, f1);
        }
    }
    return EXIT_SUCCESS;
}

int arith_image_function_1f_1_inplace(
    const char                    *ID_name,
    double                        f1,
    double (*pt2function)(double, double))
{
    IMGID img = imgid_make_from_name(ID_name);
    resolveIMGID(&img, ERRMODE_WARN, dcimg, dcnimg);
    int ret = arith_image_function_1f_1_inplace_IMGID(&img, f1, pt2function);
    if(img.ID == -1)
    {
        return RETURN_FAILURE;
    }
    imgid_free(&img);
    return ret;
}

int arith_image_function_1ff_1_IMGID(
    IMGID                         *imgin,
    double                        f1,
    double                        f2,
    IMGID                         *imgout,
    double (*pt2function)(double, double, double))
{
    if(imgin->im == NULL)
    {
        return RETURN_FAILURE;
    }

    imgout->mdt->naxis = imgin->md->naxis;
    for(uint8_t i = 0; i < imgin->md->naxis; i++)
    {
        imgout->mdt->size[i] = imgin->md->size[i];
    }
    imgout->mdt->datatype = (imgin->md->datatype == _DATATYPE_DOUBLE) ? _DATATYPE_DOUBLE :
                            _DATATYPE_FLOAT;

    if(imgout->im == NULL)
    {
        imgout->im = (IMAGE *) calloc(1, sizeof(IMAGE));
    }
    else
    {
        if(imgout->im->md && imgout->im->md->shared == 1)
        {
            ImageStreamIO_closeIm(imgout->im);
        }
        else
        {
            ImageStreamIO_destroyIm(imgout->im);
        }
    }
    imgid_mkimage(imgout);

    uint64_t nelement = imgin->md->nelement;
#ifdef _OPENMP
    #pragma omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)
#endif
    for(uint64_t ii = 0; ii < nelement; ii++)
    {
        double v = get_pixel_double(imgin->im, ii);
        if(imgout->mdt->datatype == _DATATYPE_FLOAT)
        {
            imgout->im->array.F[ii] = (float)pt2function(v, f1, f2);
        }
        else
        {
            imgout->im->array.D[ii] = pt2function(v, f1, f2);
        }
    }
    return (0);
}

int arith_image_function_1ff_1(
    const char                    *ID_name,
    double                        f1,
    double                        f2,
    const char                    *ID_out,
    double (*pt2function)(double, double, double))
{
    RESOLVE_CALL_CLEANUP(ID_name, ID_out,
                         arith_image_function_1ff_1_IMGID(&_in, f1, f2, &_out, pt2function));

}

int arith_image_function_1ff_1_inplace_IMGID(
    IMGID                         *imgin,
    double                        f1,
    double                        f2,
    double (*pt2function)(double, double, double))
{
    uint64_t nelement = imgin->im->md[0].nelement;
#ifdef _OPENMP
    #pragma omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)
#endif
    for(uint64_t ii = 0; ii < nelement; ii++)
    {
        double v = get_pixel_double(imgin->im, ii);
        if(imgin->im->md[0].datatype == _DATATYPE_FLOAT)
        {
            imgin->im->array.F[ii] = (float)pt2function(v, f1, f2);
        }
        else if(imgin->im->md[0].datatype == _DATATYPE_DOUBLE)
        {
            imgin->im->array.D[ii] = pt2function(v, f1, f2);
        }
    }
    return (0);
}

int arith_image_function_1ff_1_inplace(
    const char                    *ID_name,
    double                        f1,
    double                        f2,
    double (*pt2function)(double, double, double))
{
    IMGID img = imgid_make_from_name(ID_name);
    resolveIMGID(&img, ERRMODE_WARN, dcimg, dcnimg);
    int ret = arith_image_function_1ff_1_inplace_IMGID(&img, f1, f2, pt2function);
    if(img.ID == -1)
    {
        return RETURN_FAILURE;
    }
    imgid_free(&img);
    return ret;
}

/* Specialized optimized arithmetic functions */

/* ---------------------------------------------------------- */
/* Unary optimized: calls float/double math directly          */
/* ---------------------------------------------------------- */
// Migrated to im_math_unary.c

// Migrated to im_math_basic.c

// Migrated to im_math_logic.c
