/**
 * @file    imfunctions.c
 * @brief   Per-pixel function dispatch for image arith
 *
 * Central dispatch engine for applying scalar math
 * functions to image pixels. Contains generic
 * function-pointer variants and macro-stamped
 * optimized variants for common operations.
 *
 * Architecture:
 *  - Generic variants accept a function pointer and
 *    loop over all datatypes via else-if chains.
 *  - Optimized variants (generated by
 *    STAMP_BINARY_2_1 / STAMP_BINARY_1F_1 /
 *    STAMP_UNARY_1_1 macros) inline the operation
 *    for SIMD vectorization.
 *
 * Naming convention:
 *  - arith_image_function_im_im__d_d   — unary
 *    (image → image).
 *  - arith_image_function_imd_im__dd_d — image +
 *    scalar → image.
 *  - arith_image_function_imim_im__dd_d — image +
 *    image → image.
 *  - _IMGID suffix = modern IMGID API.

 *  - _inplace suffix = result overwrites input.
 */


#include <math.h>

#ifdef MILK_NO_CLI
#include "CLIcore_standalone.h"
#else
#include "libmilkdata/milkdata.h"
#include "milkDebugTools.h"
#endif

#include "libmilkcommon/milk_compiler.h"
#include "COREMOD_memory/COREMOD_memory.h"
#include "imfunctions.h"

// Suppress -Wunknown-pragmas for _Pragma("omp ...") expansions
// when OpenMP is globally disabled in the build.
#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#endif

#include "image_arith__im_f__im.h"
#include "mathfuncs.h"

#ifdef _OPENMP
#include <omp.h>
#define OMP_NELEMENT_LIMIT 100000
#endif

/**
 * @brief Read any-type pixel as double
 *
 * Runtime datatype dispatch for a single pixel.
 * Used by generic (non-stamped) dispatch paths.
 *
 * @param im     Image pointer
 * @param index  Pixel index
 * @return Pixel value cast to double
 */
static inline double get_pixel_double(
    IMAGE *im, uint64_t index)
{
    switch(im->md[0].datatype)
    {
        case _DATATYPE_UINT8:   return (double)im->array.UI8[index];
        case _DATATYPE_INT8:    return (double)im->array.SI8[index];
        case _DATATYPE_UINT16:  return (double)im->array.UI16[index];
        case _DATATYPE_INT16:   return (double)im->array.SI16[index];
        case _DATATYPE_UINT32:  return (double)im->array.UI32[index];
        case _DATATYPE_INT32:   return (double)im->array.SI32[index];
        case _DATATYPE_UINT64:  return (double)im->array.UI64[index];
        case _DATATYPE_INT64:   return (double)im->array.SI64[index];
        case _DATATYPE_FLOAT:   return (double)im->array.F[index];
        case _DATATYPE_DOUBLE:  return (double)im->array.D[index];
        default: return 0.0;
    }
}

/* ------------------------------------------------------------------------- */
/* Functions for bison / flex                                                */
/* im : image
  d : double

  function_<inputformat>_<outputformat>__<math function input>_<math function output>

  examples:
  function_imim__dd_d  : input is (image, image), applies double,double -> double function

  ------------------------------------------------------------------------- */

/**
 * @brief Apply unary function to image (IMGID API)
 *
 * For each pixel: out[i] = func( (double)in[i] ).
 * Output inherits input dimensions; output type is
 * FLOAT unless input is DOUBLE.
 *
 * @param imgin        Input image
 * @param imgout       Output image (created if NULL)
 * @param pt2function  Scalar function double→double
 * @return RETURN_SUCCESS or RETURN_FAILURE
 */
errno_t arith_image_function_im_im__d_d_IMGID(
    IMGID *imgin,
    IMGID *imgout,
    double (*pt2function)(double))
{
    if (imgin->im == NULL) { return RETURN_FAILURE; }

    DEBUG_TRACEPOINT("arith_image_function_d_d  %s %s\n", imgin->name, imgout->name);

    imgout->mdt->naxis = imgin->md->naxis;
    for(uint8_t i = 0; i < imgin->md->naxis; i++)
    {
        imgout->mdt->size[i] = imgin->md->size[i];
    }

    imgout->mdt->datatype = _DATATYPE_FLOAT;
    if(imgin->md->datatype == _DATATYPE_DOUBLE)
    {
        imgout->mdt->datatype = _DATATYPE_DOUBLE;
    }
    
    if (imgout->im == NULL) {
        imgout->im = (IMAGE*) calloc(1, sizeof(IMAGE));
    } else {
        if (imgout->im->md && imgout->im->md->shared == 1) ImageStreamIO_closeIm(imgout->im); else ImageStreamIO_destroyIm(imgout->im);
    }
    imgid_mkimage(imgout);

    uint_fast64_t nelement = imgin->md->nelement;
    uint8_t       datatype = imgin->md->datatype;

#ifdef _OPENMP
    #pragma omp parallel if (nelement > OMP_NELEMENT_LIMIT)
    {
#endif

    if(datatype == _DATATYPE_UINT8)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(uint_fast64_t ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.UI8[ii]));
        }
    }
    else if(datatype == _DATATYPE_UINT16)
    {
        uint16_t * MILK_RESTRICT out_ptr __attribute__((unused)) = MILK_ASSUME_ALIGNED(imgout->im->array.UI16);
        const uint16_t * MILK_RESTRICT in_ptr = MILK_ASSUME_ALIGNED(imgin->im->array.UI16);
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(uint_fast64_t ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(in_ptr[ii]));
        }
    }
    else if(datatype == _DATATYPE_UINT32)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(uint_fast64_t ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.UI32[ii]));
        }
    }
    else if(datatype == _DATATYPE_UINT64)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(uint_fast64_t ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.UI64[ii]));
        }
    }
    else if(datatype == _DATATYPE_INT8)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(uint_fast64_t ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.SI8[ii]));
        }
    }
    else if(datatype == _DATATYPE_INT16)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(uint_fast64_t ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.SI16[ii]));
        }
    }
    else if(datatype == _DATATYPE_INT32)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(uint_fast64_t ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.SI32[ii]));
        }
    }
    else if(datatype == _DATATYPE_INT64)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(uint_fast64_t ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.SI64[ii]));
        }
    }
    else if(datatype == _DATATYPE_FLOAT)
    {
        float * MILK_RESTRICT out_ptr = MILK_ASSUME_ALIGNED(imgout->im->array.F);
        const float * MILK_RESTRICT in_ptr = MILK_ASSUME_ALIGNED(imgin->im->array.F);
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(uint_fast64_t ii = 0; ii < nelement; ii++)
        {
            out_ptr[ii] =
                (float) pt2function((double)(in_ptr[ii]));
        }
    }
    else if(datatype == _DATATYPE_DOUBLE)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(uint_fast64_t ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.D[ii] =
                pt2function(imgin->im->array.D[ii]);
        }
    }
#ifdef _OPENMP
    }
#endif

    DEBUG_TRACEPOINT("arith_image_function_d_d  DONE\n");

    return RETURN_SUCCESS;
}

/**
 * @brief Apply unary function to image (string API)
 *
 * Resolves image names to IMGIDs, then delegates
 * to the _IMGID variant.
 *
 * @param ID_name       Input image name
 * @param ID_out        Output image name
 * @param pt2function   Scalar function
 * @return RETURN_SUCCESS or RETURN_FAILURE
 */
errno_t arith_image_function_im_im__d_d(
    const char *__restrict ID_name,
    const char *__restrict ID_out,
    double (*pt2function)(double))
{
    IMGID imgin  = imgid_make_from_name(ID_name);
    IMGID imgout = imgid_make_from_name(ID_out);

    resolveIMGID(&imgin, ERRMODE_ABORT, dcimg, dcnimg);
    resolveIMGID(&imgout, ERRMODE_NULL, dcimg, dcnimg);
    
    if (imgout.ID == -1) {
        imgout.mdt->shared = dcshareddft;
        imgout.mdt->NBkw = NB_KEYWNODE_MAX;
    }

    errno_t ret = arith_image_function_im_im__d_d_IMGID(&imgin,
        &imgout,
        pt2function);
    
    if (imgout.ID == -1 && imgout.im != NULL) {
        RegisterIMGID(&imgout, dcimg, dcnimg);
    }
    imgid_free(&imgin);
    imgid_free(&imgout);
    
    return ret;
}

/**
 * @brief Apply image+scalar function (IMGID API)
 *
 * For each pixel: out[i] = func( (double)in[i], v0 ).
 *
 * @param imgin        Input image
 * @param v0           Scalar constant
 * @param imgout       Output image
 * @param pt2function  Binary function (double,double)
 * @return RETURN_SUCCESS or RETURN_FAILURE
 */
errno_t arith_image_function_imd_im__dd_d_IMGID(
    IMGID *imgin,
    double v0,
    IMGID *imgout,
    double (*pt2function)(double, double))
{
    long ii;

    if (imgin->im == NULL) { return RETURN_FAILURE; }

    imgout->mdt->naxis = imgin->md->naxis;
    for(int i = 0; i < imgin->md->naxis; i++)
    {
        imgout->mdt->size[i] = imgin->md->size[i];
    }

    imgout->mdt->datatype = _DATATYPE_FLOAT;
    if(imgin->md->datatype == _DATATYPE_DOUBLE)
    {
        imgout->mdt->datatype = _DATATYPE_DOUBLE;
    }
    
    if (imgout->im == NULL) {
        imgout->im = (IMAGE*) calloc(1, sizeof(IMAGE));
    } else {
        if (imgout->im->md && imgout->im->md->shared == 1) ImageStreamIO_closeIm(imgout->im); else ImageStreamIO_destroyIm(imgout->im);
    }
    imgid_mkimage(imgout);

    uint_fast64_t nelement = imgin->md->nelement;
    uint8_t       datatype = imgin->md->datatype;

#ifdef _OPENMP
    #pragma omp parallel if (nelement > OMP_NELEMENT_LIMIT)
    {
#endif

    if(datatype == _DATATYPE_UINT8)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] =
                (float) pt2function((double)(imgin->im->array.UI8[ii]),
                                    v0);
        }
    }
    else if(datatype == _DATATYPE_UINT16)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.UI16[ii]),
                                          v0);
        }
    }
    else if(datatype == _DATATYPE_UINT32)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.UI32[ii]),
                                          v0);
        }
    }
    else if(datatype == _DATATYPE_UINT64)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.UI64[ii]),
                                          v0);
        }
    }
    else if(datatype == _DATATYPE_INT8)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] =
                (float) pt2function((double)(imgin->im->array.SI8[ii]),
                                    v0);
        }
    }
    else if(datatype == _DATATYPE_INT16)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.SI16[ii]),
                                          v0);
        }
    }
    else if(datatype == _DATATYPE_INT32)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.SI32[ii]),
                                          v0);
        }
    }
    else if(datatype == _DATATYPE_INT64)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.SI64[ii]),
                                          v0);
        }
    }
    else if(datatype == _DATATYPE_FLOAT)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] =
                (float) pt2function((double)(imgin->im->array.F[ii]),
                                    v0);
        }
    }
    else if(datatype == _DATATYPE_DOUBLE)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.D[ii] =
                pt2function(imgin->im->array.D[ii], v0);
        }
    }
#ifdef _OPENMP
    }
#endif

    DEBUG_TRACEPOINT("arith_image_function_d_d  DONE\n");

    return RETURN_SUCCESS;
}

/**
 * @brief Apply image+scalar function (string API)
 *
 * @param ID_name       Input image name
 * @param v0            Scalar constant
 * @param ID_out        Output image name
 * @param pt2function   Binary function
 * @return RETURN_SUCCESS or RETURN_FAILURE
 */
errno_t arith_image_function_imd_im__dd_d(
    const char *__restrict ID_name,
    double      v0,
    const char *__restrict ID_out,
    double (*pt2function)(double, double))
{
    IMGID imgin  = imgid_make_from_name(ID_name);
    IMGID imgout = imgid_make_from_name(ID_out);
    
    resolveIMGID(&imgin, ERRMODE_ABORT, dcimg, dcnimg);
    resolveIMGID(&imgout, ERRMODE_NULL, dcimg, dcnimg);

    if (imgout.ID == -1) {
        imgout.mdt->shared = dcshareddft;
        imgout.mdt->NBkw = NB_KEYWNODE_MAX;
    }

    errno_t ret = arith_image_function_imd_im__dd_d_IMGID(&imgin,
        v0,
        &imgout,
        pt2function);
    
    if (imgout.ID == -1 && imgout.im != NULL) {
        RegisterIMGID(&imgout, dcimg, dcnimg);
    }
    imgid_free(&imgin);
    imgid_free(&imgout);
    return ret;
}

/**
 * @brief Apply image+2-scalar function (IMGID API)
 *
 * For each pixel: out[i] = func(in[i], v0, v1).
 * Used for Ptrunc (clamp to [v0, v1]).
 *
 * @param imgin        Input image
 * @param v0           First scalar
 * @param v1           Second scalar
 * @param imgout       Output image
 * @param pt2function  Ternary function
 * @return RETURN_SUCCESS or RETURN_FAILURE
 */
errno_t arith_image_function_imdd_im__ddd_d_IMGID(
    IMGID      *imgin,
    double      v0,
    double      v1,
    IMGID      *imgout,
    double (*pt2function)(double,
                          double,
                          double))
{
    long      ii;

    if (imgin->im == NULL) { return RETURN_FAILURE; }

    imgout->mdt->naxis = imgin->md->naxis;
    for(int i = 0; i < imgin->md->naxis; i++)
    {
        imgout->mdt->size[i] = imgin->md->size[i];
    }

    imgout->mdt->datatype = _DATATYPE_FLOAT;
    if(imgin->md->datatype == _DATATYPE_DOUBLE)
    {
        imgout->mdt->datatype = _DATATYPE_DOUBLE;
    }
    
    if (imgout->im == NULL) {
        imgout->im = (IMAGE*) calloc(1, sizeof(IMAGE));
    } else {
        if (imgout->im->md && imgout->im->md->shared == 1) ImageStreamIO_closeIm(imgout->im); else ImageStreamIO_destroyIm(imgout->im);
    }
    imgid_mkimage(imgout);

    uint_fast64_t nelement = imgin->md->nelement;
    uint8_t       datatype = imgin->md->datatype;

#ifdef _OPENMP
    #pragma omp parallel if (nelement > OMP_NELEMENT_LIMIT)
    {
#endif

    if(datatype == _DATATYPE_UINT8)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] =
                (float) pt2function((double)(imgin->im->array.UI8[ii]),
                                    v0,
                                    v1);
        }
    }
    else if(datatype == _DATATYPE_UINT16)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.UI16[ii]),
                                          v0,
                                          v1);
        }
    }
    else if(datatype == _DATATYPE_UINT32)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.UI32[ii]),
                                          v0,
                                          v1);
        }
    }
    else if(datatype == _DATATYPE_UINT64)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.UI64[ii]),
                                          v0,
                                          v1);
        }
    }
    else if(datatype == _DATATYPE_INT8)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] =
                (float) pt2function((double)(imgin->im->array.SI8[ii]),
                                    v0,
                                    v1);
        }
    }
    else if(datatype == _DATATYPE_INT16)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.SI16[ii]),
                                          v0,
                                          v1);
        }
    }
    else if(datatype == _DATATYPE_INT32)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.SI32[ii]),
                                          v0,
                                          v1);
        }
    }
    else if(datatype == _DATATYPE_INT64)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] = (float) pt2function(
                                          (double)(imgin->im->array.SI64[ii]),
                                          v0,
                                          v1);
        }
    }
    else if(datatype == _DATATYPE_FLOAT)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] =
                (float) pt2function((double)(imgin->im->array.F[ii]),
                                    v0,
                                    v1);
        }
    }
    else if(datatype == _DATATYPE_DOUBLE)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.D[ii] =
                pt2function(imgin->im->array.D[ii], v0, v1);
        }
    }
#ifdef _OPENMP
    }
#endif

    DEBUG_TRACEPOINT("arith_image_function_d_d  DONE\n");

    return RETURN_SUCCESS;
}

/**
 * @brief Apply image+2-scalar function (string API)
 */
errno_t arith_image_function_imdd_im__ddd_d(
    const char *ID_name,
    double      v0,
    double      v1,
    const char *ID_out,
    double (*pt2function)(double,
                          double,
                          double))
{
    IMGID imgin  = imgid_make_from_name(ID_name);
    IMGID imgout = imgid_make_from_name(ID_out);
    
    resolveIMGID(&imgin, ERRMODE_ABORT, dcimg, dcnimg);
    resolveIMGID(&imgout, ERRMODE_NULL, dcimg, dcnimg);
    
    if (imgout.ID == -1) {
        imgout.mdt->shared = dcshareddft;
        imgout.mdt->NBkw = NB_KEYWNODE_MAX;
    }

    errno_t ret = arith_image_function_imdd_im__ddd_d_IMGID(&imgin,
        v0,
        v1,
        &imgout,
        pt2function);

    if (imgout.ID == -1 && imgout.im != NULL) {
        RegisterIMGID(&imgout, dcimg, dcnimg);
    }
    imgid_free(&imgin);
    imgid_free(&imgout);
    return ret;
}

/* ------------------------------------------------------------------------- */
/* image  -> image                                                           */
/* ------------------------------------------------------------------------- */

errno_t arith_image_function_1_1_byID(imageID ID,
                                      imageID IDout,
                                      double (*pt2function)(double))
{
    uint32_t *naxes = NULL;
    long      naxis;
    long      ii;
    long      nelement;
    uint8_t   datatype;
    //, datatypeout;
    long i;

    //  printf("arith_image_function_1_1\n");

    datatype = dcimg[ID].md[0].datatype;
    naxis    = dcimg[ID].md[0].naxis;
    naxes    = (uint32_t *) malloc(sizeof(uint32_t) * naxis);
    if(naxes == NULL)
    {
        PRINT_ERROR("malloc() error");
        exit(0);
    }

    for(i = 0; i < naxis; i++)
    {
        naxes[i] = dcimg[ID].md[0].size[i];
    }

    //    datatypeout = _DATATYPE_FLOAT;
    //    if(datatype == _DATATYPE_DOUBLE)
    //        datatypeout = _DATATYPE_DOUBLE;

    free(naxes);

    nelement = dcimg[ID].md[0].nelement;

#ifdef _OPENMP
    #pragma omp parallel if (nelement > OMP_NELEMENT_LIMIT)
    {
#endif

        if(datatype == _DATATYPE_UINT8)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                dcimg[IDout].array.F[ii] =
                    pt2function((double)(dcimg[ID].array.UI8[ii]));
            }
        }
        else if(datatype == _DATATYPE_UINT16)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                dcimg[IDout].array.F[ii] =
                    pt2function((double)(dcimg[ID].array.UI16[ii]));
            }
        }
        else if(datatype == _DATATYPE_UINT32)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                dcimg[IDout].array.F[ii] =
                    pt2function((double)(dcimg[ID].array.UI32[ii]));
            }
        }
        else if(datatype == _DATATYPE_UINT64)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                dcimg[IDout].array.F[ii] =
                    pt2function((double)(dcimg[ID].array.UI64[ii]));
            }
        }
        else if(datatype == _DATATYPE_INT8)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                dcimg[IDout].array.F[ii] =
                    pt2function((double)(dcimg[ID].array.SI8[ii]));
            }
        }
        else if(datatype == _DATATYPE_INT16)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                dcimg[IDout].array.F[ii] =
                    pt2function((double)(dcimg[ID].array.SI16[ii]));
            }
        }
        else if(datatype == _DATATYPE_INT32)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                dcimg[IDout].array.F[ii] =
                    pt2function((double)(dcimg[ID].array.SI32[ii]));
            }
        }
        else if(datatype == _DATATYPE_INT64)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                dcimg[IDout].array.F[ii] =
                    pt2function((double)(dcimg[ID].array.SI64[ii]));
            }
        }
        else if(datatype == _DATATYPE_FLOAT)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                dcimg[IDout].array.F[ii] =
                    pt2function((double)(dcimg[ID].array.F[ii]));
            }
        }
        else if(datatype == _DATATYPE_DOUBLE)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                dcimg[IDout].array.D[ii] =
                    (double) pt2function((double)(dcimg[ID].array.D[ii]));
            }
        }
#ifdef _OPENMP
    }
#endif

    return RETURN_SUCCESS;
}

errno_t arith_image_function_1_1_IMGID(IMGID *imgin,
                                       IMGID *imgout,
                                       double (*pt2function)(double))
{
    long ii;

    if (imgin->im == NULL) { return RETURN_FAILURE; }

    imgout->mdt->naxis = imgin->md->naxis;
    for(int i = 0; i < imgin->md->naxis; i++)
    {
        imgout->mdt->size[i] = imgin->md->size[i];
    }

    imgout->mdt->datatype = _DATATYPE_FLOAT;
    if(imgin->md->datatype == _DATATYPE_DOUBLE)
    {
        imgout->mdt->datatype = _DATATYPE_DOUBLE;
    }
    
    if (imgout->im == NULL) {
        imgout->im = (IMAGE*) calloc(1, sizeof(IMAGE));
    } else {
        if (imgout->im->md && imgout->im->md->shared == 1) ImageStreamIO_closeIm(imgout->im); else ImageStreamIO_destroyIm(imgout->im);
    }
    imgid_mkimage(imgout);

    uint_fast64_t nelement = imgin->md->nelement;
    uint8_t       datatype = imgin->md->datatype;

#ifdef _OPENMP
    #pragma omp parallel if (nelement > OMP_NELEMENT_LIMIT)
    {
#endif

    if(datatype == _DATATYPE_UINT8)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] =
                pt2function((double)(imgin->im->array.UI8[ii]));
        }
    }
    else if(datatype == _DATATYPE_UINT16)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] =
                pt2function((double)(imgin->im->array.UI16[ii]));
        }
    }
    else if(datatype == _DATATYPE_UINT32)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] =
                pt2function((double)(imgin->im->array.UI32[ii]));
        }
    }
    else if(datatype == _DATATYPE_UINT64)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] =
                pt2function((double)(imgin->im->array.UI64[ii]));
        }
    }
    else if(datatype == _DATATYPE_INT8)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] =
                pt2function((double)(imgin->im->array.SI8[ii]));
        }
    }
    else if(datatype == _DATATYPE_INT16)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] =
                pt2function((double)(imgin->im->array.SI16[ii]));
        }
    }
    else if(datatype == _DATATYPE_INT32)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] =
                pt2function((double)(imgin->im->array.SI32[ii]));
        }
    }
    else if(datatype == _DATATYPE_INT64)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] =
                pt2function((double)(imgin->im->array.SI64[ii]));
        }
    }
    else if(datatype == _DATATYPE_FLOAT)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.F[ii] =
                pt2function((double)(imgin->im->array.F[ii]));
        }
    }
    else if(datatype == _DATATYPE_DOUBLE)
    {
#ifdef _OPENMP
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            imgout->im->array.D[ii] =
                (double) pt2function((double)(imgin->im->array.D[ii]));
        }
    }
#ifdef _OPENMP
    }
#endif

    return RETURN_SUCCESS;
}

errno_t arith_image_function_1_1(const char *ID_name,
                                 const char *ID_out,
                                 double (*pt2function)(double))
{
    IMGID imgin  = imgid_make_from_name(ID_name);
    IMGID imgout = imgid_make_from_name(ID_out);
    
    resolveIMGID(&imgin, ERRMODE_ABORT, dcimg, dcnimg);
    resolveIMGID(&imgout, ERRMODE_NULL, dcimg, dcnimg);

    if (imgout.ID == -1) {
        imgout.mdt->shared = dcshareddft;
        imgout.mdt->NBkw = NB_KEYWNODE_MAX;
    }

    errno_t ret = arith_image_function_1_1_IMGID(&imgin, &imgout, pt2function);
    
    if (imgout.ID == -1 && imgout.im != NULL) {
        RegisterIMGID(&imgout, dcimg, dcnimg);
    }
    imgid_free(&imgin);
    imgid_free(&imgout);
    return ret;
}

// imagein -> imagein (in place)
errno_t arith_image_function_1_1_inplace_IMGID(IMGID *imgin,
        double (*pt2function)(double))
{
    long    ii;
    long    nelement;
    uint8_t datatype;
    //, datatypeout;

    // printf("arith_image_function_1_1_inplace\n");

    datatype = imgin->im->md->datatype;

    //datatypeout = _DATATYPE_FLOAT;
    //if(datatype == _DATATYPE_DOUBLE)
    //   datatypeout = _DATATYPE_DOUBLE;

    nelement = imgin->im->md->nelement;

    imgin->im->md->write = 0;
#ifdef _OPENMP
    #pragma omp parallel if (nelement > OMP_NELEMENT_LIMIT)
    {
#endif

        if(datatype == _DATATYPE_UINT8)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                imgin->im->array.F[ii] =
                    pt2function((double)(imgin->im->array.UI8[ii]));
            }
        }
        else if(datatype == _DATATYPE_UINT16)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                imgin->im->array.F[ii] =
                    pt2function((double)(imgin->im->array.UI16[ii]));
            }
        }
        else if(datatype == _DATATYPE_UINT32)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                imgin->im->array.F[ii] =
                    pt2function((double)(imgin->im->array.UI32[ii]));
            }
        }
        else if(datatype == _DATATYPE_UINT64)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                imgin->im->array.F[ii] =
                    pt2function((double)(imgin->im->array.UI64[ii]));
            }
        }
        else if(datatype == _DATATYPE_INT8)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                imgin->im->array.F[ii] =
                    pt2function((double)(imgin->im->array.SI8[ii]));
            }
        }
        else if(datatype == _DATATYPE_INT16)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                imgin->im->array.F[ii] =
                    pt2function((double)(imgin->im->array.SI16[ii]));
            }
        }
        else if(datatype == _DATATYPE_INT32)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                imgin->im->array.F[ii] =
                    pt2function((double)(imgin->im->array.SI32[ii]));
            }
        }
        else if(datatype == _DATATYPE_INT64)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                imgin->im->array.F[ii] =
                    pt2function((double)(imgin->im->array.SI64[ii]));
            }
        }
        else if(datatype == _DATATYPE_FLOAT)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                imgin->im->array.F[ii] =
                    pt2function((double)(imgin->im->array.F[ii]));
            }
        }
        else if(datatype == _DATATYPE_DOUBLE)
        {
#ifdef _OPENMP
            #pragma omp for simd
#endif
            for(ii = 0; ii < nelement; ii++)
            {
                imgin->im->array.D[ii] =
                    (double) pt2function((double)(imgin->im->array.D[ii]));
            }
        }

#ifdef _OPENMP
    }
#endif

    imgin->im->md->write = 0;
    imgin->im->md->cnt0++;

    return RETURN_SUCCESS;
}

// imagein -> imagein (in place)
errno_t arith_image_function_1_1_inplace(const char *ID_name,
        double (*pt2function)(double))
{
    IMGID img = imgid_make_from_name(ID_name);
    resolveIMGID(&img, ERRMODE_ABORT, dcimg, dcnimg);
    errno_t ret = arith_image_function_1_1_inplace_IMGID(&img, pt2function);
    imgid_free(&img);
    return ret;
}

/* ------------------------------------------------------------------------- */
/* image, image  -> image                                                    */
/* ------------------------------------------------------------------------- */

errno_t arith_image_function_2_1_IMGID(
    IMGID *inimg1,
    IMGID *inimg2,
    IMGID *outimg,
    double (*pt2function)(double, double)
)
{
    DEBUG_TRACE_FSTART();

    if (inimg1->im == NULL || inimg2->im == NULL) { return RETURN_FAILURE; }

    if( outimg->im == NULL)
    {
        imgid_copy(inimg1, outimg);
    }

    // output naxis is max of inputs
    outimg->mdt->naxis = inimg1->md->naxis;
    if ( inimg2->md->naxis > inimg1->md->naxis )
    {
        outimg->mdt->naxis = inimg2->md->naxis;
    }

    // axis expansion flags
    int in1expand[3];
    int in2expand[3];

    // check which coordinate needs to be expanded in computation
    //
    uint64_t nbpix = 1;
    uint64_t nbpix1 = 1;
    uint64_t nbpix2 = 1;
    for ( uint8_t axis = 0; axis < outimg->mdt->naxis; axis++)
    {
        in1expand[axis] = 1;
        in2expand[axis] = 1;

        uint32_t size1;
        if(axis < inimg1->md->naxis)
        {
            size1 = inimg1->md->size[axis];
        }
        else
        {
            size1 = 1;
        }
        nbpix1 *= size1;

        uint32_t size2;
        if(axis < inimg2->md->naxis)
        {
            size2 = inimg2->md->size[axis];
        }
        else
        {
            size2 = 1;
        }
        nbpix2 *= size2;

        if( size1 != size2 )
        {
            if( size1 == 1 )
            {
                in1expand[axis] = 0;
                outimg->mdt->size[axis] = size2;

            }
            else if ( size2 == 1)
            {
                in2expand[axis] = 0;
                outimg->mdt->size[axis] = size1;
            }
            else
            {
                PRINT_ERROR("axis %d size %u and %u incompatible", axis, size1, size2);
                abort();
            }
        }
        nbpix *= outimg->mdt->size[axis];
    }
    for ( uint8_t axis = outimg->mdt->naxis; axis<3; axis++)
    {
        outimg->mdt->size[axis] = 1;
        in1expand[axis] = 1;
        in2expand[axis] = 1;
    }

    outimg->mdt->datatype = _DATATYPE_FLOAT; // default
    if(inimg1->md->datatype == _DATATYPE_DOUBLE)
    {
        outimg->mdt->datatype = _DATATYPE_DOUBLE;
    }
    if(inimg2->md->datatype == _DATATYPE_DOUBLE)
    {
        outimg->mdt->datatype = _DATATYPE_DOUBLE;
    }

    if (outimg->im == NULL) {
        outimg->im = (IMAGE*) calloc(1, sizeof(IMAGE));
    } else {
        ImageStreamIO_closeIm(outimg->im);
    }
    imgid_mkimage(outimg);

    // Metadata caching
    uint64_t nelement = outimg->md->nelement;
    uint8_t datatype = outimg->mdt->datatype;
    uint8_t datatype1 = inimg1->md->datatype;
    uint8_t datatype2 = inimg2->md->datatype;

    // Fast path: images have same size and layout
    int fastpath = 1;
    if (inimg1->md->naxis != inimg2->md->naxis)
    {
        fastpath = 0;
    }
    else
    {
        for (uint8_t axis = 0; axis < outimg->mdt->naxis; axis++)
        {
            if (inimg1->md->size[axis] != inimg2->md->size[axis])
            {
                fastpath = 0;
                break;
            }
        }
    }

    if (fastpath)
    {
#ifdef _OPENMP
        #pragma omp parallel if (nelement > OMP_NELEMENT_LIMIT)
        {
#endif
            if (datatype == _DATATYPE_FLOAT && datatype1 == _DATATYPE_FLOAT && datatype2 == _DATATYPE_FLOAT)
            {
                float *outptr = outimg->im->array.F;
                float *in1ptr = inimg1->im->array.F;
                float *in2ptr = inimg2->im->array.F;
#ifdef _OPENMP
                #pragma omp for simd
#endif
                for (uint64_t ii = 0; ii < nelement; ii++)
                {
                    outptr[ii] = (float)pt2function((double)in1ptr[ii], (double)in2ptr[ii]);
                }
            }
            else if (datatype == _DATATYPE_DOUBLE && datatype1 == _DATATYPE_DOUBLE && datatype2 == _DATATYPE_DOUBLE)
            {
                double *outptr = outimg->im->array.D;
                double *in1ptr = inimg1->im->array.D;
                double *in2ptr = inimg2->im->array.D;
#ifdef _OPENMP
                #pragma omp for simd
#endif
                for (uint64_t ii = 0; ii < nelement; ii++)
                {
                    outptr[ii] = pt2function(in1ptr[ii], in2ptr[ii]);
                }
            }
            else if (datatype == _DATATYPE_FLOAT)
            {
                float *outptr = outimg->im->array.F;
#ifdef _OPENMP
                #pragma omp for simd
#endif
                for (uint64_t ii = 0; ii < nelement; ii++)
                {
                    double v1 = (datatype1 == _DATATYPE_DOUBLE) ? inimg1->im->array.D[ii] :
                                (datatype1 == _DATATYPE_FLOAT) ? inimg1->im->array.F[ii] :
                                get_pixel_double(inimg1->im, ii);
                    double v2 = (datatype2 == _DATATYPE_DOUBLE) ? inimg2->im->array.D[ii] :
                                (datatype2 == _DATATYPE_FLOAT) ? inimg2->im->array.F[ii] :
                                get_pixel_double(inimg2->im, ii);
                    outptr[ii] = (float)pt2function(v1, v2);
                }
            }
            else if (datatype == _DATATYPE_DOUBLE)
            {
                double *outptr = outimg->im->array.D;
#ifdef _OPENMP
                #pragma omp for simd
#endif
                for (uint64_t ii = 0; ii < nelement; ii++)
                {
                    double v1 = (datatype1 == _DATATYPE_DOUBLE) ? inimg1->im->array.D[ii] :
                                (datatype1 == _DATATYPE_FLOAT) ? inimg1->im->array.F[ii] :
                                get_pixel_double(inimg1->im, ii);
                    double v2 = (datatype2 == _DATATYPE_DOUBLE) ? inimg2->im->array.D[ii] :
                                (datatype2 == _DATATYPE_FLOAT) ? inimg2->im->array.F[ii] :
                                get_pixel_double(inimg2->im, ii);
                    outptr[ii] = pt2function(v1, v2);
                }
            }
#ifdef _OPENMP
        }
#endif
        DEBUG_TRACE_FEXIT();
        return RETURN_SUCCESS;
    }

    // slow path with broadcasting
    uint64_t * __restrict inpix1 = (uint64_t *) malloc(sizeof(uint64_t) * nbpix);
    uint64_t * __restrict inpix2 = (uint64_t *) malloc(sizeof(uint64_t) * nbpix);

    for ( uint32_t ii = 0; ii < outimg->mdt->size[0]; ii++ )
    {
        uint32_t ii1 = ii * in1expand[0];
        uint32_t ii2 = ii * in2expand[0];

        for ( uint32_t jj = 0; jj < outimg->mdt->size[1]; jj++ )
        {
            uint32_t jj1 = jj * in1expand[1];
            uint32_t jj2 = jj * in2expand[1];

            for ( uint32_t kk = 0; kk < outimg->mdt->size[2]; kk++ )
            {
                uint64_t outpixi = ii;
                outpixi +=  jj * outimg->mdt->size[0];
                outpixi +=  kk * outimg->mdt->size[1] * outimg->mdt->size[0];

                uint32_t kk1 = kk * in1expand[2];
                uint32_t kk2 = kk * in2expand[2];

                inpix1[outpixi] =  kk1 * inimg1->md->size[1] * inimg1->md->size[0] + jj1 * inimg1->md->size[0] + ii1;
                inpix2[outpixi] =  kk2 * inimg2->md->size[1] * inimg2->md->size[0] + jj2 * inimg2->md->size[0] + ii2;
            }
        }
    }

    double * ptr1array;
    int ptr1allocate = 0;
    if ( inimg1->md->datatype == _DATATYPE_DOUBLE ) { ptr1array = inimg1->im->array.D; }
    else {
        ptr1allocate = 1;
        ptr1array = (double *) malloc(sizeof(double) * nbpix1);
        for(
            uint64_t ii = 0; ii < nbpix1; ii++) ptr1array[ii] = get_pixel_double(inimg1->im,
            ii);
    }

    double * ptr2array;
    int ptr2allocate = 0;
    if ( inimg2->md->datatype == _DATATYPE_DOUBLE ) { ptr2array = inimg2->im->array.D; }
    else {
        ptr2allocate = 1;
        ptr2array = (double *) malloc(sizeof(double) * nbpix2);
        for(
            uint64_t ii = 0; ii < nbpix2; ii++) ptr2array[ii] = get_pixel_double(inimg2->im,
            ii);
    }

    if ( outimg->mdt->datatype == _DATATYPE_FLOAT )
    {
        for(
            uint64_t ii = 0; ii < nbpix; ii++ ) outimg->im->array.F[ii] = (float)pt2function(ptr1array[inpix1[ii]],
            ptr2array[inpix2[ii]]);
    }
    else if ( outimg->mdt->datatype == _DATATYPE_DOUBLE )
    {
        for(
            uint64_t ii = 0; ii < nbpix; ii++ ) outimg->im->array.D[ii] = pt2function(ptr1array[inpix1[ii]],
            ptr2array[inpix2[ii]]);
    }

    if(ptr1allocate == 1) free(ptr1array);
    if(ptr2allocate == 1) free(ptr2array);
    free(inpix1);
    free(inpix2);

    DEBUG_TRACE_FEXIT();
    return RETURN_SUCCESS;
}

errno_t arith_img_function_2_1(
    IMGID inimg1,
    IMGID inimg2,
    IMGID *outimg,
    double (*pt2function)(double, double)
)
{
    return arith_image_function_2_1_IMGID(&inimg1, &inimg2, outimg, pt2function);
}

/* ------------------------------------------------------------------------- */
/* image, image  -> image                                                    */
/* ------------------------------------------------------------------------- */

errno_t arith_image_function_2_1(
    const char *ID_name1,
    const char *ID_name2,
    const char *ID_out,
    double (*pt2function)(double, double)
)
{
    IMGID inimg1 = imgid_make_from_name(ID_name1);
    IMGID inimg2 = imgid_make_from_name(ID_name2);
    IMGID outimg = imgid_make_from_name(ID_out);

    resolveIMGID(&inimg1, ERRMODE_ABORT, dcimg, dcnimg);
    resolveIMGID(&inimg2, ERRMODE_ABORT, dcimg, dcnimg);
    resolveIMGID(&outimg, ERRMODE_NULL, dcimg, dcnimg);

    if (outimg.ID == -1) {
        outimg.mdt->shared = dcshareddft;
        outimg.mdt->NBkw = NB_KEYWNODE_MAX;
    }

    errno_t ret = arith_image_function_2_1_IMGID(&inimg1,
        &inimg2,
        &outimg,
        pt2function);
    
    if (outimg.ID == -1 && outimg.im != NULL) {
        RegisterIMGID(&outimg, dcimg, dcnimg);
    }
    imgid_free(&inimg1);
    imgid_free(&inimg2);
    imgid_free(&outimg);
    return ret;
}

errno_t arith_image_function_2_1_inplace_byID(
    imageID ID1,
    imageID ID2,
    double (*pt2function)(double, double)
)
{
    long    ii;
    long    nelement1, nelement2, nelement;
    uint8_t datatype1, datatype2 __attribute__((unused));

    datatype1 = dcimg[ID1].md[0].datatype;
    datatype2 = dcimg[ID2].md[0].datatype;
    nelement1 = dcimg[ID1].md[0].nelement;
    nelement2 = dcimg[ID2].md[0].nelement;

    nelement = nelement1;
    if(nelement1 != nelement2)
    {
        PRINT_ERROR("images %ld and %ld have different number of elements\n",
                    ID1,
                    ID2);
        exit(0);
    }

    dcimg[ID1].md[0].write = 1;

#ifdef _OPENMP
    #pragma omp parallel if (nelement > OMP_NELEMENT_LIMIT)
    {
        #pragma omp for simd
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            double v1 = get_pixel_double(&dcimg[ID1], ii);
            double v2 = get_pixel_double(&dcimg[ID2], ii);
            if (datatype1 == _DATATYPE_FLOAT)
                dcimg[ID1].array.F[ii] = (float)pt2function(v1, v2);
            else if (datatype1 == _DATATYPE_DOUBLE)
                dcimg[ID1].array.D[ii] = pt2function(v1, v2);
        }
#ifdef _OPENMP
    }
#endif

    dcimg[ID1].md[0].write = 0;
    dcimg[ID1].md[0].cnt0++;

    return EXIT_SUCCESS;
}

errno_t arith_image_function_2_1_inplace(
    const char *ID_name1,
    const char *ID_name2,
    double (*pt2function)(double, double))
{
    imageID ID1;
    imageID ID2;

    ID1 = image_ID(ID_name1, dcimg, dcnimg);
    ID2 = image_ID(ID_name2, dcimg, dcnimg);

    arith_image_function_2_1_inplace_byID(ID1, ID2, pt2function);

    return EXIT_SUCCESS;
}

/* ------------------------------------------------------------------------- */
/* complex image, complex image  -> complex image                            */
/* ------------------------------------------------------------------------- */
// complex float (CF), complex float (CF) -> complex float (CF)
errno_t arith_image_function_CF_CF__CF(
    const char *ID_name1,
    const char *ID_name2,
    const char *ID_out,
    complex_float(*pt2function)(
        complex_float, complex_float))
{
    IMGID img1 =
        imgid_make_from_name(ID_name1);
    resolveIMGID(&img1,
                 ERRMODE_ABORT,
                 dcimg, dcnimg);

    IMGID img2 =
        imgid_make_from_name(ID_name2);
    resolveIMGID(&img2,
                 ERRMODE_ABORT,
                 dcimg, dcnimg);

    IMGID imgout =
        imgid_make_from_name(ID_out);
    imgout.mdt->naxis = img1.md->naxis;
    for(long i = 0;
        i < img1.md->naxis; i++)
    {
        imgout.mdt->size[i] =
            img1.md->size[i];
    }
    imgout.mdt->datatype =
        img1.md->datatype;
    imgout.mdt->shared = dcshareddft;
    imgout.mdt->NBkw = NB_KEYWNODE_MAX;
    imgout.im = (IMAGE *) calloc(
        1, sizeof(IMAGE));
    imgid_mkimage(&imgout);

    long nelement =
        img1.md->nelement;

#ifdef _OPENMP
    #pragma omp parallel if (nelement > OMP_NELEMENT_LIMIT)
    {
        #pragma omp for simd
#endif
        for(long ii = 0;
            ii < nelement; ii++)
        {
            imgout.im->array.CF[ii] =
                pt2function(
                    img1.im->array.CF[ii],
                    img2.im->array.CF[ii]);
        }
#ifdef _OPENMP
    }
#endif
    RegisterIMGID(&imgout, dcimg, dcnimg);
    imgid_free(&img1);
    imgid_free(&img2);
    imgid_free(&imgout);
    return RETURN_SUCCESS;
}

// complex double (CD), complex double (CD) -> complex double (CD)
errno_t arith_image_function_CD_CD__CD(
    const char *ID_name1,
    const char *ID_name2,
    const char *ID_out,
    complex_double(*pt2function)(
        complex_double, complex_double))
{
    IMGID img1 =
        imgid_make_from_name(ID_name1);
    resolveIMGID(&img1,
                 ERRMODE_ABORT,
                 dcimg, dcnimg);

    IMGID img2 =
        imgid_make_from_name(ID_name2);
    resolveIMGID(&img2,
                 ERRMODE_ABORT,
                 dcimg, dcnimg);

    IMGID imgout =
        imgid_make_from_name(ID_out);
    imgout.mdt->naxis = img1.md->naxis;
    for(long i = 0;
        i < img1.md->naxis; i++)
    {
        imgout.mdt->size[i] =
            img1.md->size[i];
    }
    imgout.mdt->datatype =
        img1.md->datatype;
    imgout.mdt->shared = dcshareddft;
    imgout.mdt->NBkw = NB_KEYWNODE_MAX;
    imgout.im = (IMAGE *) calloc(
        1, sizeof(IMAGE));
    imgid_mkimage(&imgout);

    long nelement =
        img1.md->nelement;

#ifdef _OPENMP
    #pragma omp parallel if (nelement > OMP_NELEMENT_LIMIT)
    {
        #pragma omp for simd
#endif
        for(long ii = 0;
            ii < nelement; ii++)
        {
            imgout.im->array.CD[ii] =
                pt2function(
                    img1.im->array.CD[ii],
                    img2.im->array.CD[ii]);
        }
#ifdef _OPENMP
    }
#endif
    RegisterIMGID(&imgout, dcimg, dcnimg);
    imgid_free(&img1);
    imgid_free(&img2);
    imgid_free(&imgout);
    return RETURN_SUCCESS;
}

int arith_image_function_1f_1_IMGID(IMGID *imgin, double f1, IMGID *imgout, double (*pt2function)(double, double))
{
    long ii;
    
    if (imgin->im == NULL) { return RETURN_FAILURE; }

    imgout->mdt->naxis = imgin->md->naxis;
    for(int i = 0; i < imgin->md->naxis; i++) imgout->mdt->size[i] = imgin->md->size[i];
    imgout->mdt->datatype = (imgin->md->datatype == _DATATYPE_DOUBLE) ? _DATATYPE_DOUBLE : _DATATYPE_FLOAT;
    
    if (imgout->im == NULL) {
        imgout->im = (IMAGE*) calloc(1, sizeof(IMAGE));
    } else {
        if (imgout->im->md && imgout->im->md->shared == 1) ImageStreamIO_closeIm(imgout->im); else ImageStreamIO_destroyIm(imgout->im);
    }
    imgid_mkimage(imgout);

    uint_fast64_t nelement = imgin->md->nelement;

    if (imgin->md->datatype == _DATATYPE_FLOAT && imgout->mdt->datatype == _DATATYPE_FLOAT)
    {
        float * restrict ptr = imgin->im->array.F;
        float *out = imgout->im->array.F;
#ifdef _OPENMP
    #pragma omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)
#endif
        for(ii = 0; ii < nelement; ii++)
        {
             out[ii] = (float)pt2function((double)ptr[ii], f1);
        }
    }
    else if (imgin->md->datatype == _DATATYPE_DOUBLE && imgout->mdt->datatype == _DATATYPE_DOUBLE)
    {
        double * restrict ptr = imgin->im->array.D;
        double *out = imgout->im->array.D;
#ifdef _OPENMP
    #pragma omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)
#endif
        for(ii = 0; ii < nelement; ii++)
        {
             out[ii] = pt2function(ptr[ii], f1);
        }
    }
    else
    {
#ifdef _OPENMP
    #pragma omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)
#endif
        for(ii = 0; ii < nelement; ii++)
        {
            double v = get_pixel_double(imgin->im, ii);
            if (imgout->mdt->datatype == _DATATYPE_FLOAT) imgout->im->array.F[ii] = (float)pt2function(v, f1);
            else imgout->im->array.D[ii] = pt2function(v, f1);
        }
    }
    return EXIT_SUCCESS;
}

int arith_image_function_1f_1(const char *ID_name, double f1, const char *ID_out, double (*pt2function)(double, double))
{
    IMGID imgin = imgid_make_from_name(ID_name); IMGID imgout = imgid_make_from_name(ID_out);
    
    resolveIMGID(&imgin, ERRMODE_ABORT, dcimg, dcnimg);
    resolveIMGID(&imgout, ERRMODE_NULL, dcimg, dcnimg);
    
    if (imgout.ID == -1) {
        imgout.mdt->shared = dcshareddft;
        imgout.mdt->NBkw = NB_KEYWNODE_MAX;
    }

    int ret = arith_image_function_1f_1_IMGID(&imgin, f1, &imgout, pt2function);
    
    if (imgout.ID == -1 && imgout.im != NULL) {
        RegisterIMGID(&imgout, dcimg, dcnimg);
    }
    imgid_free(&imgin);
    imgid_free(&imgout);
    return ret;
}

int arith_image_function_1f_1_inplace_IMGID(IMGID *imgin, double f1, double (*pt2function)(double, double))
{
    long ii; uint_fast64_t nelement = imgin->im->md[0].nelement;
#ifdef _OPENMP
    #pragma omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)
#endif
    for(ii = 0; ii < nelement; ii++)
    {
        double v = get_pixel_double(imgin->im, ii);
        if (imgin->im->md[0].datatype == _DATATYPE_FLOAT) imgin->im->array.F[ii] = (float)pt2function(v, f1);
        else if (imgin->im->md[0].datatype == _DATATYPE_DOUBLE) imgin->im->array.D[ii] = pt2function(v, f1);
    }
    return EXIT_SUCCESS;
}

int arith_image_function_1f_1_inplace(const char *ID_name, double f1, double (*pt2function)(double, double))
{
    IMGID img = imgid_make_from_name(ID_name);
    resolveIMGID(&img, ERRMODE_ABORT, dcimg, dcnimg);
    int ret = arith_image_function_1f_1_inplace_IMGID(&img, f1, pt2function);
    imgid_free(&img);
    return ret;
}

int arith_image_function_1ff_1_IMGID(IMGID *imgin, double f1, double f2, IMGID *imgout, double (*pt2function)(double, double, double))
{
    long ii; 
    
    if (imgin->im == NULL) { return RETURN_FAILURE; }

    imgout->mdt->naxis = imgin->md->naxis;
    for(int i = 0; i < imgin->md->naxis; i++) imgout->mdt->size[i] = imgin->md->size[i];
    imgout->mdt->datatype = (imgin->md->datatype == _DATATYPE_DOUBLE) ? _DATATYPE_DOUBLE : _DATATYPE_FLOAT;
    
    if (imgout->im == NULL) {
        imgout->im = (IMAGE*) calloc(1, sizeof(IMAGE));
    } else {
        if (imgout->im->md && imgout->im->md->shared == 1) ImageStreamIO_closeIm(imgout->im); else ImageStreamIO_destroyIm(imgout->im);
    }
    imgid_mkimage(imgout);

    uint_fast64_t nelement = imgin->md->nelement;
#ifdef _OPENMP
    #pragma omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)
#endif
    for(ii = 0; ii < nelement; ii++)
    {
        double v = get_pixel_double(imgin->im, ii);
        if (imgout->mdt->datatype == _DATATYPE_FLOAT) imgout->im->array.F[ii] = (float)pt2function(v, f1, f2);
        else imgout->im->array.D[ii] = pt2function(v, f1, f2);
    }
    return (0);
}

int arith_image_function_1ff_1(const char *ID_name, double f1, double f2, const char *ID_out, double (*pt2function)(double, double, double))
{
    IMGID imgin = imgid_make_from_name(ID_name); IMGID imgout = imgid_make_from_name(ID_out);
    
    resolveIMGID(&imgin, ERRMODE_ABORT, dcimg, dcnimg);
    resolveIMGID(&imgout, ERRMODE_NULL, dcimg, dcnimg);
    
    if (imgout.ID == -1) {
        imgout.mdt->shared = dcshareddft;
        imgout.mdt->NBkw = NB_KEYWNODE_MAX;
    }

    int ret = arith_image_function_1ff_1_IMGID(&imgin,
        f1,
        f2,
        &imgout,
        pt2function);
    
    if (imgout.ID == -1 && imgout.im != NULL) {
        RegisterIMGID(&imgout, dcimg, dcnimg);
    }
    imgid_free(&imgin);
    imgid_free(&imgout);
    return ret;
}

int arith_image_function_1ff_1_inplace_IMGID(IMGID *imgin, double f1, double f2, double (*pt2function)(double, double, double))
{
    long ii; uint_fast64_t nelement = imgin->im->md[0].nelement;
#ifdef _OPENMP
    #pragma omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)
#endif
    for(ii = 0; ii < nelement; ii++)
    {
        double v = get_pixel_double(imgin->im, ii);
        if (imgin->im->md[0].datatype == _DATATYPE_FLOAT) imgin->im->array.F[ii] = (float)pt2function(v, f1, f2);
        else if (imgin->im->md[0].datatype == _DATATYPE_DOUBLE) imgin->im->array.D[ii] = pt2function(v, f1, f2);
    }
    return (0);
}

int arith_image_function_1ff_1_inplace(const char *ID_name, double f1, double f2, double (*pt2function)(double, double, double))
{
    IMGID img = imgid_make_from_name(ID_name);
    resolveIMGID(&img, ERRMODE_ABORT, dcimg, dcnimg);
    int ret = arith_image_function_1ff_1_inplace_IMGID(&img, f1, f2, pt2function);
    imgid_free(&img);
    return ret;
}

/* Specialized optimized arithmetic functions */

/* ---------------------------------------------------------- */
/* Unary optimized: calls float/double math directly          */
/* ---------------------------------------------------------- */
#define ARITH_UNARY_OPTIMIZED_FUNCTION_CALL(         \
    name, funcname, funcname_f)                       \
errno_t arith_image_##name##_optimized_IMGID(         \
    IMGID *imgin, IMGID *imgout)                      \
{                                                     \
    DEBUG_TRACE_FSTART();                             \
    if (imgin->im == NULL)                            \
    {                                                 \
        return RETURN_FAILURE;                        \
    }                                                 \
    if (imgout->im == NULL)                           \
    {                                                 \
        imgid_copy(imgin, imgout);                    \
    }                                                 \
    if (imgout->im == NULL)                           \
    {                                                 \
        imgout->im =                                  \
            (IMAGE *) calloc(1, sizeof(IMAGE));       \
    }                                                 \
    else                                              \
    {                                                 \
        if (imgout->im->md                            \
            && imgout->im->md->shared == 1)           \
        {                                             \
            ImageStreamIO_closeIm(imgout->im);        \
        }                                             \
        else                                          \
        {                                             \
            ImageStreamIO_destroyIm(imgout->im);      \
        }                                             \
    }                                                 \
    imgid_mkimage(imgout);                            \
    if (imgout->ID == -1 && imgout->im != NULL)       \
    {                                                 \
        RegisterIMGID(imgout, dcimg, dcnimg);         \
    }                                                 \
    uint64_t nelement = imgout->md->nelement;         \
    if (imgin->md->datatype == _DATATYPE_FLOAT        \
        && imgout->mdt->datatype == _DATATYPE_FLOAT)  \
    {                                                 \
        float * MILK_RESTRICT p1 =                    \
            MILK_ASSUME_ALIGNED(imgin->im->array.F);  \
        float * MILK_RESTRICT po =                    \
            MILK_ASSUME_ALIGNED(imgout->im->array.F); \
        _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)")     \
        for (uint64_t i = 0; i < nelement; i++)       \
        {                                             \
            po[i] = funcname_f(p1[i]);                \
        }                                             \
    }                                                 \
    else if (imgin->md->datatype == _DATATYPE_DOUBLE  \
        && imgout->mdt->datatype == _DATATYPE_DOUBLE) \
    {                                                 \
        double *p1 = imgin->im->array.D;              \
        double *po = imgout->im->array.D;             \
        _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)")     \
        for (uint64_t i = 0; i < nelement; i++)       \
        {                                             \
            po[i] = funcname(p1[i]);                  \
        }                                             \
    }                                                 \
    else                                              \
    {                                                 \
        arith_image_function_1_1_IMGID(               \
            imgin, imgout, &P##name);                 \
    }                                                 \
    DEBUG_TRACE_FEXIT();                              \
    return RETURN_SUCCESS;                            \
}

ARITH_UNARY_OPTIMIZED_FUNCTION_CALL(acos, acos, acosf)
ARITH_UNARY_OPTIMIZED_FUNCTION_CALL(asin, asin, asinf)
ARITH_UNARY_OPTIMIZED_FUNCTION_CALL(atan, atan, atanf)
ARITH_UNARY_OPTIMIZED_FUNCTION_CALL(ceil, ceil, ceilf)
ARITH_UNARY_OPTIMIZED_FUNCTION_CALL(cos, cos, cosf)
ARITH_UNARY_OPTIMIZED_FUNCTION_CALL(cosh, cosh, coshf)
ARITH_UNARY_OPTIMIZED_FUNCTION_CALL(exp, exp, expf)
ARITH_UNARY_OPTIMIZED_FUNCTION_CALL(fabs, fabs, fabsf)
ARITH_UNARY_OPTIMIZED_FUNCTION_CALL(floor, floor, floorf)
ARITH_UNARY_OPTIMIZED_FUNCTION_CALL(ln, log, logf)
ARITH_UNARY_OPTIMIZED_FUNCTION_CALL(log, log10, log10f)
ARITH_UNARY_OPTIMIZED_FUNCTION_CALL(sqrt, sqrt, sqrtf)
ARITH_UNARY_OPTIMIZED_FUNCTION_CALL(sin, sin, sinf)
ARITH_UNARY_OPTIMIZED_FUNCTION_CALL(sinh, sinh, sinhf)
ARITH_UNARY_OPTIMIZED_FUNCTION_CALL(tan, tan, tanf)
ARITH_UNARY_OPTIMIZED_FUNCTION_CALL(tanh, tanh, tanhf)

#define ARITH_OPTIMIZED_FUNCTION(name, op) \
errno_t arith_image_##name##_optimized_IMGID(IMGID *imgin1, IMGID *imgin2, IMGID *imgout) \
{ \
    DEBUG_TRACE_FSTART(); \
    if (imgin1->im == NULL || imgin2->im == NULL) { return RETURN_FAILURE; } \
    if(imgout->im == NULL) imgid_copy(imgin1, imgout); \
    if (imgout->im == NULL) { imgout->im = (IMAGE*) calloc(1, sizeof(IMAGE)); } \
    else { if (imgout->im->md && imgout->im->md->shared == 1) ImageStreamIO_closeIm(imgout->im); else ImageStreamIO_destroyIm(imgout->im); } \
    imgid_mkimage(imgout); \
    if (imgout->ID == -1 && imgout->im != NULL) { RegisterIMGID(imgout, dcimg, dcnimg); } \
    uint64_t nelement = imgout->md->nelement; \
    if(imgin1->md->datatype == _DATATYPE_FLOAT && imgin2->md->datatype == _DATATYPE_FLOAT && imgout->mdt->datatype == _DATATYPE_FLOAT) \
    { \
        float * MILK_RESTRICT p1 = MILK_ASSUME_ALIGNED(imgin1->im->array.F); \
        float * MILK_RESTRICT p2 = MILK_ASSUME_ALIGNED(imgin2->im->array.F); \
        float * MILK_RESTRICT po = MILK_ASSUME_ALIGNED(imgout->im->array.F); \
        _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)") \
        for(uint64_t i=0; i<nelement; i++) po[i] = p1[i] op p2[i]; \
    } \
    else if(imgin1->md->datatype == _DATATYPE_DOUBLE && imgin2->md->datatype == _DATATYPE_DOUBLE && imgout->mdt->datatype == _DATATYPE_DOUBLE) \
    { \
        double * MILK_RESTRICT p1 = MILK_ASSUME_ALIGNED(imgin1->im->array.D); \
        double * MILK_RESTRICT p2 = MILK_ASSUME_ALIGNED(imgin2->im->array.D); \
        double * MILK_RESTRICT po = MILK_ASSUME_ALIGNED(imgout->im->array.D); \
        _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)") \
        for(uint64_t i=0; i<nelement; i++) po[i] = p1[i] op p2[i]; \
    } \
    else \
    { \
        arith_image_function_2_1_IMGID(imgin1, imgin2, imgout, &P##name); \
    } \
    DEBUG_TRACE_FEXIT(); \
    return RETURN_SUCCESS; \
}

ARITH_OPTIMIZED_FUNCTION(add, +)
ARITH_OPTIMIZED_FUNCTION(sub, -)
ARITH_OPTIMIZED_FUNCTION(mult, *)
ARITH_OPTIMIZED_FUNCTION(div, /)

#define ARITH_CST_OPTIMIZED_FUNCTION(name, op) \
errno_t arith_image_cst##name##_optimized_IMGID(IMGID *imgin, double f1, IMGID *imgout) \
{ \
    DEBUG_TRACE_FSTART(); \
    if (imgin->im == NULL) { return RETURN_FAILURE; } \
    if(imgout->im == NULL) imgid_copy(imgin, imgout); \
    if (imgout->im == NULL) { imgout->im = (IMAGE*) calloc(1, sizeof(IMAGE)); } \
    else { if (imgout->im->md && imgout->im->md->shared == 1) ImageStreamIO_closeIm(imgout->im); else ImageStreamIO_destroyIm(imgout->im); } \
    imgid_mkimage(imgout); \
    if (imgout->ID == -1 && imgout->im != NULL) { RegisterIMGID(imgout, dcimg, dcnimg); } \
    uint64_t nelement = imgout->md->nelement; \
    if(imgin->md->datatype == _DATATYPE_FLOAT && imgout->mdt->datatype == _DATATYPE_FLOAT) \
    { \
        float * MILK_RESTRICT p1 = MILK_ASSUME_ALIGNED(imgin->im->array.F); \
        float * MILK_RESTRICT po = MILK_ASSUME_ALIGNED(imgout->im->array.F); \
        float cf1 = (float)f1; \
        _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)") \
        for(uint64_t i=0; i<nelement; i++) po[i] = p1[i] op cf1; \
    } \
    else if(imgin->md->datatype == _DATATYPE_DOUBLE && imgout->mdt->datatype == _DATATYPE_DOUBLE) \
    { \
        double *p1 = imgin->im->array.D; \
        double *po = imgout->im->array.D; \
        _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)") \
        for(uint64_t i=0; i<nelement; i++) po[i] = p1[i] op f1; \
    } \
    else \
    { \
        arith_image_function_1f_1_IMGID(imgin, f1, imgout, &P##name); \
    } \
    DEBUG_TRACE_FEXIT(); \
    return RETURN_SUCCESS; \
}

ARITH_CST_OPTIMIZED_FUNCTION(add, +)
ARITH_CST_OPTIMIZED_FUNCTION(sub, -)
ARITH_CST_OPTIMIZED_FUNCTION(mult, *)
ARITH_CST_OPTIMIZED_FUNCTION(div, /)

errno_t arith_image_cstpow_optimized_IMGID(IMGID *imgin, double f1, IMGID *imgout)
{
    DEBUG_TRACE_FSTART();
    if (imgin->im == NULL) { return RETURN_FAILURE; }
    if(imgout->im == NULL) imgid_copy(imgin, imgout);
    if (imgout->im == NULL) { imgout->im = (IMAGE*) calloc(1, sizeof(IMAGE)); }
    else { if (imgout->im->md && imgout->im->md->shared == 1) ImageStreamIO_closeIm(imgout->im); else ImageStreamIO_destroyIm(imgout->im); }
    imgid_mkimage(imgout);
    if (imgout->ID == -1 && imgout->im != NULL) { RegisterIMGID(imgout, dcimg, dcnimg); }
    uint64_t nelement = imgout->md->nelement;
    if(imgin->md->datatype == _DATATYPE_FLOAT && imgout->mdt->datatype == _DATATYPE_FLOAT)
    {
        float * MILK_RESTRICT p1 = MILK_ASSUME_ALIGNED(imgin->im->array.F);
        float * MILK_RESTRICT po = MILK_ASSUME_ALIGNED(imgout->im->array.F);
        float cf1 = (float)f1;
        if (f1 == 0.0) {
            _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)")
            for(uint64_t i=0; i<nelement; i++) po[i] = 1.0f;
        } else if (f1 == 1.0) {
            _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)")
            for(uint64_t i=0; i<nelement; i++) po[i] = p1[i];
        } else if (f1 == 0.5) {
            _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)")
            for(uint64_t i=0; i<nelement; i++) po[i] = sqrtf(p1[i]);
        } else if (f1 == 2.0) {
            _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)")
            for(uint64_t i=0; i<nelement; i++) po[i] = p1[i] * p1[i];
        } else {
            _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)")
            for(uint64_t i=0; i<nelement; i++) po[i] = powf(p1[i], cf1);
        }
    }
    else if(imgin->md->datatype == _DATATYPE_DOUBLE && imgout->mdt->datatype == _DATATYPE_DOUBLE)
    {
        double * MILK_RESTRICT p1 = MILK_ASSUME_ALIGNED(imgin->im->array.D);
        double * MILK_RESTRICT po = MILK_ASSUME_ALIGNED(imgout->im->array.D);
        if (f1 == 0.0) {
            _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)")
            for(uint64_t i=0; i<nelement; i++) po[i] = 1.0;
        } else if (f1 == 1.0) {
            _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)")
            for(uint64_t i=0; i<nelement; i++) po[i] = p1[i];
        } else if (f1 == 0.5) {
            _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)")
            for(uint64_t i=0; i<nelement; i++) po[i] = sqrt(p1[i]);
        } else if (f1 == 2.0) {
            _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)")
            for(uint64_t i=0; i<nelement; i++) po[i] = p1[i] * p1[i];
        } else {
            _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)")
            for(uint64_t i=0; i<nelement; i++) po[i] = pow(p1[i], f1);
        }
    }
    else
    {
        arith_image_function_1f_1_IMGID(imgin, f1, imgout, &Ppow);
    }
    DEBUG_TRACE_FEXIT();
    return RETURN_SUCCESS;
}

#define ARITH_OPTIMIZED_FUNCTION_CALL(name, funcname, funcname_f) \
errno_t arith_image_##name##_optimized_IMGID(IMGID *imgin1, IMGID *imgin2, IMGID *imgout) \
{ \
    DEBUG_TRACE_FSTART(); \
    if (imgin1->im == NULL || imgin2->im == NULL) { return RETURN_FAILURE; } \
    if(imgout->im == NULL) imgid_copy(imgin1, imgout); \
    if (imgout->im == NULL) { imgout->im = (IMAGE*) calloc(1, sizeof(IMAGE)); } \
    else { if (imgout->im->md && imgout->im->md->shared == 1) ImageStreamIO_closeIm(imgout->im); else ImageStreamIO_destroyIm(imgout->im); } \
    imgid_mkimage(imgout); \
    if (imgout->ID == -1 && imgout->im != NULL) { RegisterIMGID(imgout, dcimg, dcnimg); } \
    uint64_t nelement = imgout->md->nelement; \
    if(imgin1->md->datatype == _DATATYPE_FLOAT && imgin2->md->datatype == _DATATYPE_FLOAT && imgout->mdt->datatype == _DATATYPE_FLOAT) \
    { \
        float * MILK_RESTRICT p1 = MILK_ASSUME_ALIGNED(imgin1->im->array.F); \
        float * MILK_RESTRICT p2 = MILK_ASSUME_ALIGNED(imgin2->im->array.F); \
        float * MILK_RESTRICT po = MILK_ASSUME_ALIGNED(imgout->im->array.F); \
        _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)") \
        for(uint64_t i=0; i<nelement; i++) po[i] = funcname_f(p1[i], p2[i]); \
    } \
    else if(imgin1->md->datatype == _DATATYPE_DOUBLE && imgin2->md->datatype == _DATATYPE_DOUBLE && imgout->mdt->datatype == _DATATYPE_DOUBLE) \
    { \
        double * MILK_RESTRICT p1 = MILK_ASSUME_ALIGNED(imgin1->im->array.D); \
        double * MILK_RESTRICT p2 = MILK_ASSUME_ALIGNED(imgin2->im->array.D); \
        double * MILK_RESTRICT po = MILK_ASSUME_ALIGNED(imgout->im->array.D); \
        _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)") \
        for(uint64_t i=0; i<nelement; i++) po[i] = funcname(p1[i], p2[i]); \
    } \
    else \
    { \
        arith_image_function_2_1_IMGID(imgin1, imgin2, imgout, &P##name); \
    } \
    DEBUG_TRACE_FEXIT(); \
    return RETURN_SUCCESS; \
}

ARITH_OPTIMIZED_FUNCTION_CALL(pow, pow, powf)
ARITH_OPTIMIZED_FUNCTION_CALL(fmod, fmod, fmodf)
ARITH_OPTIMIZED_FUNCTION_CALL(minv, fmin, fminf)
ARITH_OPTIMIZED_FUNCTION_CALL(maxv, fmax, fmaxf)

/* ---------------------------------------------------------- */
/* Binary optimized: comparison/logic with expression          */
/* ---------------------------------------------------------- */
#define ARITH_OPTIMIZED_FUNCTION_EXPR(               \
    name, expr_f, expr_d)                             \
errno_t arith_image_##name##_optimized_IMGID(         \
    IMGID *imgin1,                                    \
    IMGID *imgin2,                                    \
    IMGID *imgout)                                    \
{                                                     \
    DEBUG_TRACE_FSTART();                             \
    if (imgin1->im == NULL                            \
        || imgin2->im == NULL)                        \
    {                                                 \
        return RETURN_FAILURE;                        \
    }                                                 \
    if (imgout->im == NULL)                           \
    {                                                 \
        imgid_copy(imgin1, imgout);                   \
    }                                                 \
    if (imgout->im == NULL)                           \
    {                                                 \
        imgout->im =                                  \
            (IMAGE *) calloc(1, sizeof(IMAGE));       \
    }                                                 \
    else                                              \
    {                                                 \
        if (imgout->im->md                            \
            && imgout->im->md->shared == 1)           \
        {                                             \
            ImageStreamIO_closeIm(imgout->im);        \
        }                                             \
        else                                          \
        {                                             \
            ImageStreamIO_destroyIm(imgout->im);      \
        }                                             \
    }                                                 \
    imgid_mkimage(imgout);                            \
    if (imgout->ID == -1 && imgout->im != NULL)       \
    {                                                 \
        RegisterIMGID(imgout, dcimg, dcnimg);         \
    }                                                 \
    uint64_t nelement = imgout->md->nelement;         \
    if (imgin1->md->datatype == _DATATYPE_FLOAT       \
        && imgin2->md->datatype == _DATATYPE_FLOAT    \
        && imgout->mdt->datatype == _DATATYPE_FLOAT)  \
    {                                                 \
        const float * MILK_RESTRICT p1 =              \
            MILK_ASSUME_ALIGNED(                      \
                imgin1->im->array.F);                 \
        const float * MILK_RESTRICT p2 =              \
            MILK_ASSUME_ALIGNED(                      \
                imgin2->im->array.F);                 \
        float * MILK_RESTRICT po =                    \
            MILK_ASSUME_ALIGNED(                      \
                imgout->im->array.F);                 \
        _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)")     \
        for (uint64_t i = 0; i < nelement; i++)       \
        {                                             \
            po[i] = (expr_f);                         \
        }                                             \
    }                                                 \
    else if (imgin1->md->datatype == _DATATYPE_DOUBLE \
        && imgin2->md->datatype == _DATATYPE_DOUBLE   \
        && imgout->mdt->datatype == _DATATYPE_DOUBLE) \
    {                                                 \
        const double * MILK_RESTRICT p1 =             \
            MILK_ASSUME_ALIGNED(                      \
                imgin1->im->array.D);                 \
        const double * MILK_RESTRICT p2 =             \
            MILK_ASSUME_ALIGNED(                      \
                imgin2->im->array.D);                 \
        double * MILK_RESTRICT po =                   \
            MILK_ASSUME_ALIGNED(                      \
                imgout->im->array.D);                 \
        _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)")     \
        for (uint64_t i = 0; i < nelement; i++)       \
        {                                             \
            po[i] = (expr_d);                         \
        }                                             \
    }                                                 \
    else                                              \
    {                                                 \
        arith_image_function_2_1_IMGID(               \
            imgin1, imgin2, imgout, &P##name);        \
    }                                                 \
    DEBUG_TRACE_FEXIT();                              \
    return RETURN_SUCCESS;                            \
}

ARITH_OPTIMIZED_FUNCTION_EXPR(
    testlt,
    (p1[i] < p2[i]) ? 1.0f : 0.0f,
    (p1[i] < p2[i]) ? 1.0 : 0.0)
ARITH_OPTIMIZED_FUNCTION_EXPR(
    testmt,
    (p1[i] >= p2[i]) ? 1.0f : 0.0f,
    (p1[i] >= p2[i]) ? 1.0 : 0.0)
ARITH_OPTIMIZED_FUNCTION_EXPR(
    teste,
    (p1[i] == p2[i]) ? 1.0f : 0.0f,
    (p1[i] == p2[i]) ? 1.0 : 0.0)
ARITH_OPTIMIZED_FUNCTION_EXPR(
    testne,
    (p1[i] != p2[i]) ? 1.0f : 0.0f,
    (p1[i] != p2[i]) ? 1.0 : 0.0)
ARITH_OPTIMIZED_FUNCTION_EXPR(
    testle,
    (p1[i] <= p2[i]) ? 1.0f : 0.0f,
    (p1[i] <= p2[i]) ? 1.0 : 0.0)
ARITH_OPTIMIZED_FUNCTION_EXPR(
    testge,
    (p1[i] >= p2[i]) ? 1.0f : 0.0f,
    (p1[i] >= p2[i]) ? 1.0 : 0.0)
ARITH_OPTIMIZED_FUNCTION_EXPR(
    and,
    ((p1[i] != 0.0f) && (p2[i] != 0.0f))
        ? 1.0f : 0.0f,
    ((p1[i] != 0.0) && (p2[i] != 0.0))
        ? 1.0 : 0.0)
ARITH_OPTIMIZED_FUNCTION_EXPR(
    or,
    ((p1[i] != 0.0f) || (p2[i] != 0.0f))
        ? 1.0f : 0.0f,
    ((p1[i] != 0.0) || (p2[i] != 0.0))
        ? 1.0 : 0.0)

/* ---------------------------------------------------------- */
/* Const-scalar optimized: comparison/logic with expression    */
/* ---------------------------------------------------------- */
#define ARITH_CST_OPTIMIZED_FUNCTION_EXPR(            \
    name, expr_f, expr_d)                             \
errno_t arith_image_cst##name##_optimized_IMGID(      \
    IMGID *imgin,                                     \
    double f1,                                        \
    IMGID *imgout)                                    \
{                                                     \
    DEBUG_TRACE_FSTART();                             \
    if (imgin->im == NULL)                            \
    {                                                 \
        return RETURN_FAILURE;                        \
    }                                                 \
    if (imgout->im == NULL)                           \
    {                                                 \
        imgid_copy(imgin, imgout);                    \
    }                                                 \
    if (imgout->im == NULL)                           \
    {                                                 \
        imgout->im =                                  \
            (IMAGE *) calloc(1, sizeof(IMAGE));       \
    }                                                 \
    else                                              \
    {                                                 \
        if (imgout->im->md                            \
            && imgout->im->md->shared == 1)           \
        {                                             \
            ImageStreamIO_closeIm(imgout->im);        \
        }                                             \
        else                                          \
        {                                             \
            ImageStreamIO_destroyIm(imgout->im);      \
        }                                             \
    }                                                 \
    imgid_mkimage(imgout);                            \
    if (imgout->ID == -1 && imgout->im != NULL)       \
    {                                                 \
        RegisterIMGID(imgout, dcimg, dcnimg);         \
    }                                                 \
    uint64_t nelement = imgout->md->nelement;         \
    if (imgin->md->datatype == _DATATYPE_FLOAT        \
        && imgout->mdt->datatype == _DATATYPE_FLOAT)  \
    {                                                 \
        const float * MILK_RESTRICT p1 =              \
            MILK_ASSUME_ALIGNED(imgin->im->array.F);  \
        float * MILK_RESTRICT po =                    \
            MILK_ASSUME_ALIGNED(imgout->im->array.F); \
        float cf1 = (float) f1;                       \
        _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)")     \
        for (uint64_t i = 0; i < nelement; i++)       \
        {                                             \
            po[i] = (expr_f);                         \
        }                                             \
    }                                                 \
    else if (imgin->md->datatype == _DATATYPE_DOUBLE  \
        && imgout->mdt->datatype == _DATATYPE_DOUBLE) \
    {                                                 \
        const double * MILK_RESTRICT p1 =             \
            MILK_ASSUME_ALIGNED(imgin->im->array.D);  \
        double * MILK_RESTRICT po =                   \
            MILK_ASSUME_ALIGNED(imgout->im->array.D); \
        _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)")     \
        for (uint64_t i = 0; i < nelement; i++)       \
        {                                             \
            po[i] = (expr_d);                         \
        }                                             \
    }                                                 \
    else                                              \
    {                                                 \
        arith_image_function_1f_1_IMGID(              \
            imgin, f1, imgout, &P##name);             \
    }                                                 \
    DEBUG_TRACE_FEXIT();                              \
    return RETURN_SUCCESS;                            \
}

ARITH_CST_OPTIMIZED_FUNCTION_EXPR(
    testlt,
    (p1[i] < cf1) ? 1.0f : 0.0f,
    (p1[i] < f1) ? 1.0 : 0.0)
ARITH_CST_OPTIMIZED_FUNCTION_EXPR(
    testmt,
    (p1[i] >= cf1) ? 1.0f : 0.0f,
    (p1[i] >= f1) ? 1.0 : 0.0)
ARITH_CST_OPTIMIZED_FUNCTION_EXPR(
    teste,
    (p1[i] == cf1) ? 1.0f : 0.0f,
    (p1[i] == f1) ? 1.0 : 0.0)
ARITH_CST_OPTIMIZED_FUNCTION_EXPR(
    testne,
    (p1[i] != cf1) ? 1.0f : 0.0f,
    (p1[i] != f1) ? 1.0 : 0.0)
ARITH_CST_OPTIMIZED_FUNCTION_EXPR(
    testle,
    (p1[i] <= cf1) ? 1.0f : 0.0f,
    (p1[i] <= f1) ? 1.0 : 0.0)
ARITH_CST_OPTIMIZED_FUNCTION_EXPR(
    testge,
    (p1[i] >= cf1) ? 1.0f : 0.0f,
    (p1[i] >= f1) ? 1.0 : 0.0)
ARITH_CST_OPTIMIZED_FUNCTION_EXPR(
    and,
    ((p1[i] != 0.0f) && (cf1 != 0.0f))
        ? 1.0f : 0.0f,
    ((p1[i] != 0.0) && (f1 != 0.0))
        ? 1.0 : 0.0)
ARITH_CST_OPTIMIZED_FUNCTION_EXPR(
    or,
    ((p1[i] != 0.0f) || (cf1 != 0.0f))
        ? 1.0f : 0.0f,
    ((p1[i] != 0.0) || (f1 != 0.0))
        ? 1.0 : 0.0)

/* ---------------------------------------------------------- */
/* Unary optimized: comparison with expression                 */
/* ---------------------------------------------------------- */
#define ARITH_UNARY_OPTIMIZED_FUNCTION_EXPR(          \
    name, expr_f, expr_d)                             \
errno_t arith_image_##name##_optimized_IMGID(         \
    IMGID *imgin, IMGID *imgout)                      \
{                                                     \
    DEBUG_TRACE_FSTART();                             \
    if (imgin->im == NULL)                            \
    {                                                 \
        return RETURN_FAILURE;                        \
    }                                                 \
    if (imgout->im == NULL)                           \
    {                                                 \
        imgid_copy(imgin, imgout);                    \
    }                                                 \
    if (imgout->im == NULL)                           \
    {                                                 \
        imgout->im =                                  \
            (IMAGE *) calloc(1, sizeof(IMAGE));       \
    }                                                 \
    else                                              \
    {                                                 \
        if (imgout->im->md                            \
            && imgout->im->md->shared == 1)           \
        {                                             \
            ImageStreamIO_closeIm(imgout->im);        \
        }                                             \
        else                                          \
        {                                             \
            ImageStreamIO_destroyIm(imgout->im);      \
        }                                             \
    }                                                 \
    imgid_mkimage(imgout);                            \
    if (imgout->ID == -1 && imgout->im != NULL)       \
    {                                                 \
        RegisterIMGID(imgout, dcimg, dcnimg);         \
    }                                                 \
    uint64_t nelement = imgout->md->nelement;         \
    if (imgin->md->datatype == _DATATYPE_FLOAT        \
        && imgout->mdt->datatype == _DATATYPE_FLOAT)  \
    {                                                 \
        const float * MILK_RESTRICT p1 =              \
            MILK_ASSUME_ALIGNED(imgin->im->array.F);  \
        float * MILK_RESTRICT po =                    \
            MILK_ASSUME_ALIGNED(imgout->im->array.F); \
        _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)")     \
        for (uint64_t i = 0; i < nelement; i++)       \
        {                                             \
            po[i] = (expr_f);                         \
        }                                             \
    }                                                 \
    else if (imgin->md->datatype == _DATATYPE_DOUBLE  \
        && imgout->mdt->datatype == _DATATYPE_DOUBLE) \
    {                                                 \
        const double * MILK_RESTRICT p1 =             \
            MILK_ASSUME_ALIGNED(imgin->im->array.D);  \
        double * MILK_RESTRICT po =                   \
            MILK_ASSUME_ALIGNED(imgout->im->array.D); \
        _Pragma("omp parallel for simd if (nelement > OMP_NELEMENT_LIMIT)")     \
        for (uint64_t i = 0; i < nelement; i++)       \
        {                                             \
            po[i] = (expr_d);                         \
        }                                             \
    }                                                 \
    else                                              \
    {                                                 \
        arith_image_function_1_1_IMGID(               \
            imgin, imgout, &P##name);                 \
    }                                                 \
    DEBUG_TRACE_FEXIT();                              \
    return RETURN_SUCCESS;                            \
}

ARITH_UNARY_OPTIMIZED_FUNCTION_EXPR(
    positive,
    (p1[i] > 0.0f) ? 1.0f : 0.0f,
    (p1[i] > 0.0) ? 1.0 : 0.0)